### ISSUE TITLE
Disable FAM rotation or change icon when open

### ISSUE THREAD

**Issue by dan-zx** [Clans/FloatingActionButton#1]
I have a FAM with a custom icon that looks wired when the FAM rotates:
![screenshot_1](https://cloud.githubusercontent.com/assets/4072025/6811730/947f202a-d22f-11e4-829e-393491521006.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/4072025/6811733/998eea14-d22f-11e4-9cc1-006d4b854cd1.png)

Is there a way to disable rotation or change the icon (let's say the 'X' icon) when the FAM opens?

**Comment by Clans** [comment]
I'll try to find some time to add an option to disable FAM rotation by the end of the week.

**Comment by Clans** [comment]
Added an option to disable FAM icon rotation. See [Changelog](https://github.com/Clans/FloatingActionButton/wiki/Changelog).

**Comment by dan-zx** [comment]
Thanks! :)

**Comment by WojciechKo** [comment]
How about change icon during menu opening? I there any chance to get this feature?

**Comment by Clans** [comment]
Please see the green menu button on the demo video. Is that what you need?

**Comment by WojciechKo** [comment]
Exactly!
Thank you good sir, take one star from me.

**Comment by dtarianyk** [comment]
Thanks. The code is in the sample project. ;)

**Comment by Clans** [comment]
Thanks. The code is in the sample project. ;)

**Comment by AtlasRider** [comment]
From the Changelog:

FAM.setIconAnimated(false);
