### ISSUE TITLE
Floating Button can't set label !

### ISSUE THREAD

**Issue by longnbse02652** [Clans/FloatingActionButton#100]
<com.github.clans.fab.FloatingActionButton
        android:id="@+id/fab_camera"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="112dp"
        android:layout_marginRight="8dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/ic_addmysen_camera"
        fab:fab_colorNormal="#00bcd4"
        fab:fab_colorPressed="@color/colorPrimary"
        fab:fab_colorRipple="@color/colorPrimaryDark"
        fab:fab_label="撮影"
        fab:fab_size="mini" />

I dont know where wrong ?

**Comment by bdaykid** [comment]
Hi, try replacing 

fab:fab_label="撮影" with
app:fab_label="撮影"

replace the fab with app. Good Luck.

**Comment by KynoYang** [comment]
I guess it's because the fab isn't in a fam. 

Actually, I have the same problem, though I know the reason after reading the source code. 

However, I wonder if you would support to addLabel for tabs that not in a fam?

**Comment by Clans** [comment]
I don't see any reason doing it in a library. You can easily place any `TextView` near the FAB by yourself.

**Comment by KynoYang** [comment]
@Clans OK, I agree.

**Comment by yusufsaktian** [comment]
Help me sir, what must added code in my fragment which fab menu can be clicked for move activity?


import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.support.v7.app.ActionBarActivity;
import android.widget.Button;
import android.widget.TextView;

public class Contoh extends Fragment {
    
    private final static String COUNTRY = "country";

    public static Fragment newInstance(String country) {
        Fragment fragment = new CountryFragment();

        Bundle args = new Bundle();
        args.putString(COUNTRY, country);
        fragment.setArguments(args);

        return fragment;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_contoh, container, false);
        

        return view;
    }

}

my xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" xmlns:fab="http://schemas.android.com/apk/res-auto"
    xmlns:app="http://schemas.android.com/apk/res-auto" android:background="@color/putih">


    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"

        android:background="@color/birumaterial"
        android:baselineAligned="false"
        android:orientation="vertical" >



        <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="8.0dip"
            android:layout_marginRight="8.0dip"
            android:layout_marginTop="8.0dip"
            android:gravity="center"
            android:orientation="horizontal" >


        </LinearLayout>


        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/margin_dalamkartu_vertikal"
            android:layout_marginLeft="40dip"
            android:layout_marginRight="15dip"


            android:textStyle="bold"
            android:textColor="@color/putih"
            android:textSize="25sp"
            />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/margin_dalamkartu_vertikal"
            android:layout_marginLeft="40dip"
            android:layout_marginRight="15dip"


            android:textStyle="bold"
            android:textColor="@color/putih"
            android:textSize="25sp"
            />

    </LinearLayout>

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:background="@color/birumaterial"
        android:baselineAligned="false"
        android:orientation="vertical" >



        <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="8.0dip"
            android:layout_marginRight="8.0dip"
            android:layout_marginTop="8.0dip"
            android:gravity="center"
            android:orientation="horizontal" >


        </LinearLayout>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/margin_dalamkartu_vertikal"
            android:layout_marginLeft="40dip"
            android:layout_marginRight="15dip"


            android:textStyle="bold"
            android:textColor="@color/putih"
            android:textSize="25sp"
            />



    </LinearLayout>
    <FrameLayout
    android:layout_width="280dp"
    android:layout_height="371dp"
    android:layout_gravity="center"
    android:background="#F5F5F5">

    <ScrollView
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:fadingEdge="none"
        android:layout_gravity="center">

        <TableLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:stretchColumns="*"
            android:layout_gravity="center_vertical"
            >

            <TableRow
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                >

                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:id="@id/wa"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:id="@id/wi"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
            </TableRow>
            <TableRow
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" >
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
            </TableRow>
            <TableRow
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" >
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
                <at.markushi.ui.CircleButton
                    android:layout_width="20dip"
                    android:layout_height="70dip"
                    android:text="A"
                    android:textColor="@color/putih"
                    android:textStyle="bold"
                    android:textSize="@dimen/ukuran20sp"
                    app:cb_color="#E91E63"
                    app:cb_pressedRingWidth="8dip" />
            </TableRow>

        </TableLayout>

    </ScrollView>

    </FrameLayout>

    <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/menu"
        android:layout_width="131dp"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginRight="10dp"
        android:layout_marginBottom="10dp"
        android:layout_marginLeft="10dp"
        fab:menu_fab_size="normal"
        fab:menu_showShadow="true"
        fab:menu_shadowColor="#66000000"
        fab:menu_shadowRadius="4dp"
        fab:menu_shadowXOffset="1dp"
        fab:menu_shadowYOffset="3dp"
        fab:menu_colorNormal="#DA4336"
        fab:menu_colorPressed="#E75043"
        fab:menu_colorRipple="#99FFFFFF"
        fab:menu_animationDelayPerItem="50"

        fab:menu_buttonSpacing="0dp"
        fab:menu_labels_margin="0dp"
        fab:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
        fab:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
        fab:menu_labels_paddingTop="4dp"
        fab:menu_labels_paddingRight="8dp"
        fab:menu_labels_paddingBottom="4dp"
        fab:menu_labels_paddingLeft="8dp"
        fab:menu_labels_padding="8dp"
        fab:menu_labels_textColor="#FFFFFF"
        fab:menu_labels_textSize="14sp"
        fab:menu_labels_cornerRadius="3dp"
        fab:menu_labels_colorNormal="#333333"
        fab:menu_labels_colorPressed="#444444"
        fab:menu_labels_colorRipple="#66FFFFFF"
        fab:menu_labels_showShadow="true"
        fab:menu_labels_singleLine="false"
        fab:menu_labels_ellipsize="none"
        fab:menu_labels_maxLines="-1"

        fab:menu_labels_position="left"
        fab:menu_openDirection="up"
        fab:menu_backgroundColor="@android:color/transparent"

        android:layout_gravity="right|bottom">

        <com.github.clans.fab.FloatingActionButton
            android:id="@id/wo"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"

            fab:fab_size="mini"
            fab:fab_label="J-R" />
        

    </com.github.clans.fab.FloatingActionMenu>

</FrameLayout>

**Comment by Clans** [comment]
If you have a question please create a new issue and describe it.
