### ISSUE TITLE
Rotate Custom Menu icon 360 degrees rather than 180 when button is clicked

### ISSUE THREAD

**Issue by btripp** [Clans/FloatingActionButton#101]
When I set a icon like below and I click on it. The icon only rotates 180 degrees. Is there a way to set the opened icon?
![image](https://cloud.githubusercontent.com/assets/1022815/9038570/3de5a120-39c3-11e5-8876-d80850e1703a.png)

![image](https://cloud.githubusercontent.com/assets/1022815/9038563/2d5fbea8-39c3-11e5-9682-476dada58124.png)

**Comment by Clans** [comment]
Hello, you can create any your own animation like this:
https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/FloatingMenusActivity.java#L151

**Comment by Marcuccio** [comment]
Clans your link does not exist

**Comment by Clans** [comment]
That's because it was last year. :) Here is the new link: https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/MenusFragment.java#L163

**Comment by Shanto16** [comment]
can u please give me an elaborated answer please ?? sorry i am new :(
