### ISSUE TITLE
Changing Label background color

### ISSUE THREAD

**Issue by theaidorus** [Clans/FloatingActionButton#107]
hey, thanks for the amazing library! My question is that can I change the background color of the FAB label?

Thank you so much.

**Comment by MyHeartsECO** [comment]
@theaidorus That'd be awesome for this library.

If you really need to change label background, try this:
https://github.com/wangjiegulu/RapidFloatingActionButton

It has some deep issues on changing label text and icon but rest is good.

**Comment by Clans** [comment]
Yes. `FloatingActionMenu` has these xml attributes for that:
```XML
fab:menu_labels_colorNormal="#333333"
fab:menu_labels_colorPressed="#444444"
fab:menu_labels_colorRipple="#66FFFFFF"
```
or you can use a style:
```xml
fab:menu_labels_style="@style/YourCustomLabelsStyle"
```

**Comment by RajeshReddy18** [comment]
How can i stop the animation in floating point point button in android
