### ISSUE TITLE
icon after animation end

### ISSUE THREAD

**Issue by deblockt** [Clans/FloatingActionButton#108]
I have an error, I use a personal icon for the floatmenu.
But when i click on the menu, the icon at anomation end is not the "cross" icon like on you demo, but my icon is just rotated.
Have you an option for correct this issue? 

Thanks.

**Comment by Clans** [comment]
Just look into the sources please.

**Comment by bkhall** [comment]
Hey Clans, I believe he's referring to the way the green star menu button works in your video. I also wish to implement similar functionality.

I've been alt through the source and don't see a way to tell the menu button to use two different icons. Ideally, the library should handle this. We should be able to specify an initial icon of our own but have the ic_close (or rotated plus) as the default close icon.

Incidentally, telling people to read the source isn't really a solution suitable for closing an issue..

**Comment by Clans** [comment]
Adding such a method will limit the functionality. Using the way I demonstrated [here](https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/FloatingMenusActivity.java#L161) gives more flexibility to use custom animations and different custom icons.
But I will think about adding some default behavior for this.
