### ISSUE TITLE
Error with fab:

### ISSUE THREAD

**Issue by miladmofficial** [Clans/FloatingActionButton#109]
hi guys
i have some issue  with this kind of XML
fab:menu_fab_size="normal"
I've already build Gradle with this library. but XML can't parse these lines.

**Comment by Clans** [comment]
Try clean and rebuild the project.

**Comment by Spisaczek** [comment]
For anyone who clean&build solution doesn't work. 
I also faced this problem. Resolve was adding this line to my Layout:

`xmlns:fab="http://schemas.android.com/apk/res-auto"`

PS: Great lib!
