### ISSUE TITLE
Fab inside Fam onClickListener

### ISSUE THREAD

**Issue by Ioane5** [Clans/FloatingActionButton#110]
When using `onClick` attribute with `FloatingActionButton` when it's inside `FloatingActionMenu`, strange thing happens. 
`FloatingActionButtons` are becoming like "checkable".  Several `FloatingActionButtons` in `FloatingActionMenu` have `colorPressed`. 

This issue didn't happen when I used `setOnClickListener` programmatically.

This must be a bug. 
Hope it helps. 

P.S Thanks for excellent library.

**Comment by Clans** [comment]
Just set OnClickListener programmatically.
