### ISSUE TITLE
Set padding for ImageButton in FloatingActionMenu

### ISSUE THREAD

**Issue by hanihashemi** [Clans/FloatingActionButton#117]
Hi,
I use FloatingActionMenu, when i set right and bottom padding to 10dp, my button doesn't go to bottom of screen, how can i add padding just to my ImageButton not to FloatingActionMenu? (Please check the screenshot)
```xml
<com.github.clans.fab.FloatingActionMenu
            fab:menu_fab_hide_animation="@anim/hide_to_bottom"
            fab:menu_fab_show_animation="@anim/show_from_bottom"
            android:paddingBottom="10dp"
            android:paddingRight="10dp"> ....
```

![Screenshot](http://s8.postimg.org/brsrrijyt/photo_2015_09_05_15_07_49.jpg)

**Comment by andrejd** [comment]
Same here. Whenever I try to position floating menu button with paddings, annoying gap is visible.
It can be positioned correctly with shadow x/y offset without above gap, but then you have strange shadow underneath ;)

**Comment by Clans** [comment]
Try using margin for now please.

**Comment by Clans** [comment]
Hm... I used padding for the FAM and didn't saw such behavior. Could you post your code here please?

**Comment by hanihashemi** [comment]
view:
```xml
        <com.github.clans.fab.FloatingActionMenu
            android:id="@+id/floating_action_menu"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            app:menu_colorNormal="@color/accent_dark"
            app:menu_colorPressed="@color/accent"
            app:menu_colorRipple="@color/accent_light"
            fab:menu_backgroundColor="#ccffffff"
            fab:menu_fab_hide_animation="@anim/hide_to_bottom"
            fab:menu_fab_show_animation="@anim/show_from_bottom"
            android:paddingBottom="10dp"
            android:paddingRight="10dp">

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/poll_create"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_create_poll"
                app:fab_colorNormal="@color/accent_dark"
                app:fab_colorPressed="@color/accent"
                app:fab_colorRipple="@color/accent_light"
                fab:fab_label="@string/floating_button_create_poll"
                fab:fab_size="mini"
                fab:menu_colorNormal="@color/accent"/>

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/review_create"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_create_review"
                app:fab_colorNormal="@color/accent_dark"
                app:fab_colorPressed="@color/accent"
                app:fab_colorRipple="@color/accent_light"
                fab:fab_label="@string/floationg_button_create_review"
                fab:fab_size="mini"
                fab:menu_colorNormal="@color/accent"/>
```

animation hide:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<alpha xmlns:android="http://schemas.android.com/apk/res/android"
       android:duration="300"
       android:fromAlpha="1.0"
       android:interpolator="@android:interpolator/accelerate_cubic"
       android:toAlpha="0.0"/>
```

**Comment by Clans** [comment]
Didn't able to use your colors, icons and animations but here is what I've got with th rest of your code:
![device-2015-09-09-145206](https://cloud.githubusercontent.com/assets/1575275/9761002/89181324-5702-11e5-9321-21706ac42d26.png)

**Comment by hanihashemi** [comment]
I'm terribly sorry. My mistake !

I forgot to mention this happens *only* during the animation

**Comment by andrejd** [comment]
Just to be sure we are talking about same thing ... Paddings and margins are working as they should, I have gap like the one on first picture when hiding/showing FAM. When FAM is going off screen, it does not go to the nav bar ...

**Comment by hanihashemi** [comment]
@andrejd Yes, that's exactly my problem

**Comment by Clans** [comment]
Ok, I figured out the problem. There are some difficalties with animations because FAM is a ViewGroup that contains the menu toggle button and the expadning buttons with labels. I quess I'm gonna need to add some extra methods so you could choose either to animate the button only or the whole FAM.
Thanks for your help in improving the library!

**Comment by hanihashemi** [comment]
Thank you very much ;)

**Comment by MirXaTouQeer** [comment]
unable to implement
**_android:scaleType="fitCenter"_**

### view: 
` < com.github.clans.fab.FloatingActionMenu
	        android:id="@+id/fab"
	        android:layout_width="match_parent"
	        android:layout_height="match_parent"
	        android:layout_alignParentBottom="true"
	        android:layout_alignParentRight="true"
	        android:paddingRight="10dp"
	        android:paddingBottom="10dp"
	        android:paddingLeft="10dp"
	        android:tint="@color/colorPrimary"
	        fab:menu_labels_ellipsize="end"
	        fab:menu_labels_singleLine="true"
	        fab:menu_backgroundColor="#ccffffff"
	        fab:menu_colorNormal="@color/colorPrimary"
	        fab:menu_colorPressed="@color/colorPrimaryDark"
	        fab:menu_fab_label="Menu label">
	
	        <com.github.clans.fab.FloatingActionButton
	            android:id="@+id/fab_add"
	            android:layout_width="wrap_content"
	            android:layout_height="wrap_content"
	            android:src="@drawable/ic_edit_black"
				android:scaleType="fitCenter"
	            android:tint="@color/colorPrimary"
				app:backgroundTint="@color/material_grey_100"
				app:elevation="6dp"
				app:pressedTranslationZ="12dp"
				fab:fab_colorNormal="@color/colorPrimary"
	        	fab:fab_colorPressed="@color/colorPrimaryDark"
	            fab:fab_size="mini"
	            fab:fab_label="Add Number" />
	
	        <com.github.clans.fab.FloatingActionButton
	            android:id="@+id/fab_add_call_log"
	            android:layout_width="wrap_content"
	            android:layout_height="wrap_content"
	            android:tint="@color/colorPrimary"
				app:backgroundTint="@color/material_grey_100"
				app:elevation="6dp"
				app:pressedTranslationZ="12dp"
				android:src="@drawable/ic_call_history"
				android:scaleType="fitCenter"
	            fab:fab_size="mini"
	            fab:fab_label="Add from Call Log" />
	
	        <com.github.clans.fab.FloatingActionButton
	            android:id="@+id/fab_add_contact"
	            android:layout_width="wrap_content"
	            android:layout_height="wrap_content"
	            android:tint="@color/colorPrimary"
				app:backgroundTint="@color/material_grey_100"
				app:pressedTranslationZ="12dp"
				android:src="@drawable/ic_contact_black"
				android:scaleType="fitCenter"
	            fab:fab_size="mini"
	            fab:fab_label="Add from Contacts" />
	
	    </com.github.clans.fab.FloatingActionMenu>`

![screenshot from 2016-03-17 02 53 23](https://cloud.githubusercontent.com/assets/13826761/13830071/468da8d2-ebec-11e5-80c3-51ab97106e9f.png)
