### ISSUE TITLE
FAB on top of Google Map V2

### ISSUE THREAD

**Issue by nickmccomb** [Clans/FloatingActionButton#118]
When i put the Floating Action Button over the top of a Google Map it stops me from being able to interact with the map.  

The layout is match_parent for height and width, so the FAB takes up all of the screen, but on my other Fragments (without Google Maps) i can interact with Views behind the FAB.  When the FAB is on a Fragment with a Google Map i cannot interact with any Views behind the FAB.

Does anyone have a solution to this?

**Comment by nickmccomb** [comment]
So what i ended up doing was putting the fragment in an Activity with a ViewPager and put the FAB in the xml for that Activity, this allows me to interact with the map in the Fragment that the ViewPager holds

**Comment by aimanzakikagzi** [comment]
I am facing the Same Issue. Can you please provide Code example ?
