### ISSUE TITLE
Graphical issue when animating

### ISSUE THREAD

**Issue by Fleker** [Clans/FloatingActionButton#119]
After looking at this issue on Cabinet, https://github.com/afollestad/cabinet-issue-tracker/issues/245, it seems like the issue might be coming from this library.

Even when isolating the FAB, there seems to be clipping going on during the animation.

**Comment by Clans** [comment]
Could you provide your code here so I could look ta the issue?

**Comment by Fleker** [comment]
Here's an example of the layout. There's no code being used in this activity aside from hiding and showing.

    <com.github.clans.fab.FloatingActionMenu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:id="@+id/fab_actions"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="bottom|end"
    android:paddingBottom="@dimen/fab_margin_ver"
    android:paddingEnd="@dimen/fab_margin_hor"
    android:paddingRight="@dimen/fab_margin_hor"
    fab:menu_buttonSpacing="8dp"
    fab:menu_icon="@drawable/fab_add"
    fab:menu_labels_margin="4dp"
    fab:menu_labels_paddingBottom="8dp"
    fab:menu_labels_paddingLeft="12dp"
    fab:menu_labels_paddingRight="12dp"
    fab:menu_labels_paddingTop="8dp"
    fab:menu_labels_textSize="@dimen/content_textsize"
    fab:menu_openDirection="up">

    </com.github.clans.fab.FloatingActionMenu>

This is after experimenting with some other models but that glitch still occurs.

**Comment by Clans** [comment]
I used your code and can't see any bug. Here is the complete code I used:
```XML
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ListView
        android:id="@+id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity" />

    <com.github.clans.fab.FloatingActionMenu
        xmlns:fab="http://schemas.android.com/apk/res-auto"
        android:id="@+id/fab_actions"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="bottom|end"
        android:paddingBottom="10dp"
        android:paddingEnd="10dp"
        android:paddingRight="10dp"
        fab:menu_buttonSpacing="8dp"
        fab:menu_icon="@drawable/fab_add"
        fab:menu_labels_margin="4dp"
        fab:menu_labels_paddingBottom="8dp"
        fab:menu_labels_paddingLeft="12dp"
        fab:menu_labels_paddingRight="12dp"
        fab:menu_labels_paddingTop="8dp"
        fab:menu_labels_textSize="18sp"
        fab:menu_openDirection="up">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_edit"
            fab:fab_size="mini"
            fab:fab_label="Menu item 1" />

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_edit"
            fab:fab_size="mini"
            fab:fab_label="Menu item 2" />

    </com.github.clans.fab.FloatingActionMenu>

</FrameLayout>
```
And here is the results:
![device-2015-09-09-121427](https://cloud.githubusercontent.com/assets/1575275/9758053/bfb88ae6-56ec-11e5-82df-7c4179139d5e.png)

**Comment by Fleker** [comment]
Here is a sample activity I've been using:

    public class Main2Activity extends AppCompatActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.fab_menu_2);
            findViewById(R.id.fab_actions).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    FloatingActionMenu fam = (FloatingActionMenu) findViewById(R.id.fab_actions);
                    if(fam.isMenuButtonHidden())
                        fam.showMenuButton(true);
                    else
                        fam.hideMenuButton(true);
                }
            });
        }
    }

The glitch happens when you look at the show/exit animation, sorry I didn't mention that before. When you show the FAB, the shadows on the bottom and the right look like they get cut off.

**Comment by Clans** [comment]
Looks like it's the same issue as #117.

**Comment by Fleker** [comment]
Updated to 1.6.1 and implemented the `{}Menu` methods but I'm still seeing a bit of cut-off on the bottom of the menu when it animates back.

You can see the effect in this YouTube video: https://www.youtube.com/watch?v=uqxVK05HQCs

**Comment by plusCubed** [comment]
2 visual issues - icon doesn't stay in the middle while animating (new issue since 1.6), and the cut-off problem with the default scale up animation (play that video at 0.25 speed).

**Comment by Clans** [comment]
Same as #220
