### ISSUE TITLE
API 14+

### ISSUE THREAD

**Issue by adek** [Clans/FloatingActionButton#12]
I like you library but in many projects we use at the moment API 14+. Could you tell me why you choose for this library 15+? Any chances for this lib to be 14+?

**Comment by madyx** [comment]
I'm facing the same situation as explained above (and I think many more are). It'd be great to make its minimum sdk version 14+.
Anyways, great library !

**Comment by Clans** [comment]
According to [Google's statistics](https://developer.android.com/about/dashboards/index.html#Platform) it looks like there are no devices running API 14 left (or they're under the 0.1% line). I believe it would be better to bump the version of that projects to 15.

**Comment by madyx** [comment]
What a fast reply !
You're right ! I fooled myself thinking API 15 was for Android 4.1 (and thus 14 for 4.0.3 - 4.0.4).
Thanks.

**Comment by adek** [comment]
Yes. We made big update last year to our app and we've got min. API set to 14. I saw this in many other project.

Your library is based on other library which is API 14+ (https://github.com/futuresimple/android-floating-action-button), that's why I asked about it. Maybe, if you don't need to change anything in your code you can set minimum to 14. Probably your code will be OK also for API 14+. I think many devs are in similar situation - you've got project with minimum API14 and you can't change it :(

**Comment by Clans** [comment]
I'll see what I can do.

**Comment by Clans** [comment]
Done.
