### ISSUE TITLE
FAB loses its properties for layout after setting Intermediate to false

### ISSUE THREAD

**Issue by DenizUgur** [Clans/FloatingActionButton#125]
<RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/fab_container"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_fab_sync"
            fab:fab_size="normal"
            fab:fab_progress_showBackground="false"
            android:layout_gravity="bottom"
            android:layout_alignParentTop="true"
            android:layout_centerInParent="true"
            android:layout_centerHorizontal="true" />
      </RelativeLayout>

**Comment by aalap-shah** [comment]
+1

**Comment by tuhin10** [comment]
I have the same issue.

**Comment by bkhall** [comment]
+1

Seems that anything that calls through updateButtonPosition() moves the button to upper left corner of the screen.

In my case, every time I hide the progress indicator with hideProgress().

**Comment by DenisMondon** [comment]
Does someone have a fix? :)
