### ISSUE TITLE
Move FAB in CoordinatorLayout

### ISSUE THREAD

**Issue by leijdekkers** [Clans/FloatingActionButton#126]
When i put the FloatingActionMenu in a CoordinatorLayout layout with a snackbar feature the FloatingActionMenu does not move up when a snackbar is shown. Is it possible to make this library so that it works in CoordinatorLayout?

**Comment by Clans** [comment]
Please see issue #61.

**Comment by leijdekkers** [comment]
Thanks. I fixed it using the instructions in that issue! thanks!
