### ISSUE TITLE
Can't closed the menu when touchoutside

### ISSUE THREAD

**Issue by suojiang** [Clans/FloatingActionButton#128]
I've set  "menu.setClosedOnTouchOutside(true);" but when i touch the listview the menu can't closed.

<com.github.clans.fab.FloatingActionMenu
        android:id="@+id/menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="20dp"
        android:layout_marginBottom="20dp"
        android:layout_marginTop="10dp"
        fab:menu_labels_style="@style/MenuLabelsStyle"
        fab:menu_labels_showAnimation="@anim/jump_from_down"
        fab:menu_labels_hideAnimation="@anim/jump_to_down"
        fab:menu_animationDelayPerItem="0"
        fab:menu_shadowColor="@color/shadowColor"
        fab:menu_colorNormal="@color/colorPrimary"
        fab:menu_colorPressed="@color/colorPrimary_Pressed"
        fab:menu_colorRipple="@color/colorPrimary_Ripple">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/add_new_fans"
            fab:fab_label="@string/add_new_fans"
            style="@style/MenuButtonsStyle" />

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/send_group_msg"
            fab:fab_label="@string/send_group_msg"
            style="@style/MenuButtonsStyle" />
    </com.github.clans.fab.FloatingActionMenu>

menu = (FloatingActionMenu) view.findViewById(R.id.menu);
        fab1 = (FloatingActionButton) view.findViewById(R.id.fab1);
        fab2 = (FloatingActionButton) view.findViewById(R.id.fab2);

        fab1.setOnClickListener(this);
        fab2.setOnClickListener(this);

        menu.hideMenuButton(false);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                menu.showMenuButton(true);
            }
        }, 400);
        menu.setClosedOnTouchOutside(true);

**Comment by Clans** [comment]
You have to set FAM's width and height as `match_parent`.

**Comment by suojiang** [comment]
thanks for your help.

**Comment by gokhannaim** [comment]
great,thanks man!

**Comment by mihaylov2805** [comment]
thanks
