### ISSUE TITLE
BackgroundColor in Code ?

### ISSUE THREAD

**Issue by thenightdev** [Clans/FloatingActionButton#13]
Hi, 

first of all very nice work :+1: , but I have a question. 
How can I set the BackgroudColor of the Menu (and the Button) in Code ?
I have tried everything and have also seen the sample project, but got no solution.
I have to change the color based on the current image!

-> mFloatingActionMenu.setBackgroundColor(palette.getVibrantColor(0x00000));

This statement gives not the wanted effect
![quickmemo _2015-04-06-22-26-33](https://cloud.githubusercontent.com/assets/11823977/7011767/4344e3a2-dcac-11e4-8cb1-c32a25c8ea86.png)
https://www.dropbox.com/s/za13sexhmmynkiw/QuickMemo%2B_2015-04-06-22-26-33.png?dl=0

Need Help

**Comment by Clans** [comment]
Under "BackgroudColor of the Menu" you mean the background color of the menu labels?

**Comment by thenightdev** [comment]
No I mean the button itself. You call the button that contains other buttons, a menu,  that's why I wrote menu.  But thanks for the fast reply.  It would be very nice if you could help me out

**Comment by Clans** [comment]
Will try to publish an update in a couple of days.

**Comment by thenightdev** [comment]
Thanks 
👍

**Comment by Clans** [comment]
Done. See [Changelog](https://github.com/Clans/FloatingActionButton/wiki/Changelog).
