### ISSUE TITLE
SVG drawables

### ISSUE THREAD

**Issue by fmeneuhe** [Clans/FloatingActionButton#131]
Hi,
I use this SVG icons library:
https://github.com/mikepenz/Android-Iconics

Do you think is possible to integrate FloatingActionButton to use this lib (or similar one) to use SVG icons?
So the icons can be resized to any size and can be easy colored to any color. 
Thanks

**Comment by Clans** [comment]
I think yes. Just fork my library and implement the functionality you need. :)

**Comment by fmeneuhe** [comment]
Hi Dmytro,
I have never used GitHub before. If I do a fork, it will be only on my
computer or can I upload to the GitHub repository?
Thanks


2015-09-22 10:34 GMT+02:00 Dmytro Tarianyk <notifications@github.com>:

**Comment by Clans** [comment]
It will create a repository in your account and clone the code into it. You'll be able to use it as a normal repository.

**Comment by fmeneuhe** [comment]
Right. So if I want that the code be available for the community, what do I have to do?

**Comment by lolkittens** [comment]
@fmeneuhe [Github's guide may help you out.](https://guides.github.com/activities/hello-world/)
