### ISSUE TITLE
Disable animation for menu

### ISSUE THREAD

**Issue by kristijandraca** [Clans/FloatingActionButton#132]
Is possible to remove animation from FAM?

**Comment by lolkittens** [comment]
Are you talking about the main button's icon animation? [FloatingActionMenu#setIconAnimated](https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/java/com/github/clans/fab/FloatingActionMenu.java#L766)

**Comment by kristijandraca** [comment]
Sorry I didn't saw that
