### ISSUE TITLE
Support for API 14

### ISSUE THREAD

**Issue by tuhin10** [Clans/FloatingActionButton#135]
Is it possible to support API 14 ?  I only need expand/collapse/FAM click functionality.

**Comment by tuhin10** [comment]
I just checked the library build.gradle its mention min sdk = 14(minSdkVersion 14)
Can any one confirm if its support API 14?

**Comment by lolobosse** [comment]
Hey,

https://github.com/Clans/FloatingActionButton/issues/12

**Comment by tuhin10** [comment]
@lolobosse  Thanx
