### ISSUE TITLE
How to add FAB buttons programatically?

### ISSUE THREAD

**Issue by moradgholi** [Clans/FloatingActionButton#14]
Hi,
I need to add or remove the FAB buttons programmatically, so I've added the menu in the XML file and then i tried to add the FloatingActionButtons programmatically with calling addView method on the menu.
The problem is that the menu does't show the new fab buttons because the children have created on onMeasure. I tried to call the requestLayout() method on the menu but nothing changed.
How can i handle it ?

**Comment by Clans** [comment]
I'll add that in the next release.

**Comment by Frykky** [comment]
Have you added in 1.4.0?

**Comment by Clans** [comment]
Not yet, it was mostly bug fix release.

**Comment by pawelByszewski** [comment]
+1 that is big problem also for me

**Comment by Frykky** [comment]
CircularFloatingButton of oguzbilgener do it if you want... but your library is better :dancer:
