### ISSUE TITLE
label of actionbutton added programmatically on actionmenu is not clickable

### ISSUE THREAD

**Issue by amatig** [Clans/FloatingActionButton#140]
Hi,
if I add button on menu programmatically, label of button don't have click listener of button.

FloatingActionButton m1 = new FloatingActionButton(getActivity());
m1.setLabelText(elem);
m1.setButtonSize(FloatingActionButton.SIZE_MINI);
m1.setColorNormalResId(R.color.help);
m1.setColorPressedResId(R.color.help);
m1.setColorRippleResId(R.color.colorPrimaryDark);
m1.setShadowColorResource(R.color.dark_gray2);
 m1.setOnClickListener(new FloatingActionButton.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        ....
                    }
});

...
...
mFabMenu.addMenuButton(m1);

**Comment by Clans** [comment]
Please see the #121 issue.
