### ISSUE TITLE
Floating Action Menu Padding affect hide animation

### ISSUE THREAD

**Issue by TPeterW** [Clans/FloatingActionButton#147]
If Floating Action Menu has padding, hideMenuButton animation with hide_to_bottom or jump_to_bottom will not go all the way to bottom, but will start disapearing from where padding is set (like cut off by the line of padding).

Same code would however work for Floating Action Button. Believe this is a bug. Would try to get screenshot on.

**Comment by Clans** [comment]
Try using the `showMenu()` and `hideMenu()` methods.

**Comment by TPeterW** [comment]
Thank you!
