### ISSUE TITLE
Add a public setIcon() method to FloatingActionMenu

### ISSUE THREAD

**Issue by fmeneuhe** [Clans/FloatingActionButton#148]
Hi,
Could you please add a public setIcon() to the FloatingActionMenu to set the icon programmatically?
Thanks

**Comment by mavencode01** [comment]
+1

I currently need to set the FloatingActionMenu icon  to different icons when opened and closed but
unfortunately, setIcon is not implemented.
Better yet, setOpenIcon, setCloseIcon methods will be useful to add.

Thanks

**Comment by oliverlj** [comment]
Like it is defined in the specification : http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3TmpnUHVKRV9DU0E/components-buttons-fab-transition_speeddial_02.webm

**Comment by Clans** [comment]
Please have a look at the [sample](https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/FloatingMenusActivity.java#L161). Is that what you need?

**Comment by mavencode01** [comment]
Awesome!

Can we add it to the documentation for everyone else
