### ISSUE TITLE
Background issues while using colorRipple

### ISSUE THREAD

**Issue by adek** [Clans/FloatingActionButton#15]
Background issues while using custom pressed and ripple colors.

This is my FAB layout:
<com.github.clans.fab.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_margin="16dp"
        android:src="@drawable/ic_add_white_24dp"
        fab:fab_colorNormal="@color/theme_accent"
        fab:fab_colorPressed="@color/theme_accent_pressed"
        fab:fab_colorRipple="@color/theme_accent_ripple" />

![issue-fab1](https://cloud.githubusercontent.com/assets/963361/7043200/18f4fa28-dde8-11e4-8c74-4eb270c4f0a9.png)

Tested on Nexus 6 (Android 5.1).

When I remove colorPressed and colorRipple strange rectangles are gone.

**Comment by Kennyc1012** [comment]
I have had users also report this issue, however I only have the colorNormal and colorPressed set, not colorRipple. Here is the [layout file](https://github.com/Kennyc1012/OpenImgur/blob/master/src/main/res/layout/upload_menu.xml) containing the buttons, the FloatingActionMenu is the button which is showing the rectangles

**Comment by Clans** [comment]
Working on it. Will try to publish a fix as soon as I'll have some free time.

**Comment by adek** [comment]
Yes. I thought that removing colorRipple fixed the problem but it wasn't fixed. 
The problem is visible on Android 5+ devices. On my old Android with 4.4 button and focus looks good.

**Comment by itiboi** [comment]
Can also confirm it on Android 5.1 (Nexus 5).

**Comment by adek** [comment]
Does anyone have workaround for this bug?
I'm trying to find what's going on. It looks like this is only Android 5.1 (API22) bug. On my Genymotion device Android 5.0 (API21) it looks fine, ripple effect is also OK.

This is somehow connected to focus (not the ripple effect).

**Comment by Clans** [comment]
It's finally here! See the [Changelog](https://github.com/Clans/FloatingActionButton/wiki/Changelog) for new awesome improvements and bug fixes.
