### ISSUE TITLE
Any way to put TypeFace to a Label?

### ISSUE THREAD

**Issue by gonharry** [Clans/FloatingActionButton#151]
Hi, first of all: thanks and congrats for this proyect.

My question: is it possible to put TypeFace to a ```label``` (for both, button and menu) ?

Any ideas or some update with this feature?

**Comment by Clans** [comment]
Sorry, there is no such functionality at the moment.

**Comment by igozhenko** [comment]
I guess, you can try to use [Caligraphy](https://github.com/chrisjenx/Calligraphy)

**Comment by Rainer-Lang** [comment]
Maybe Android-Iconics of Mike Penz could help you.

**Comment by Clans** [comment]
Implemented in v1.6.4
