### ISSUE TITLE
Permanent tint in label and button

### ISSUE THREAD

**Issue by jzeferino** [Clans/FloatingActionButton#153]
i have a video showing a problem when you have FAB inside a viewpager.
the tint of the labels and buttons remain wrong after dissmis a click.
please watch:  https://vid.me/11zE

**Comment by jzeferino** [comment]
@Clans any recommendation to bypass this bug?
@Clans any release date for this bug solving?

**Comment by Clans** [comment]
Sorry, can't tell you any date. Have no time right now to take a look. You can make a PR with a fix to make it faster.

**Comment by jzeferino** [comment]
ok, i will try to find the problem.
Can you tell me the main classes to stop by?

**Comment by jzeferino** [comment]
@Clans as sugested, i fixed the issue and made a pull request.

**Comment by jzeferino** [comment]
@Clans can you check the PR please?

**Comment by drinfernoo** [comment]
@jzeferino Good luck, doesn't seem like the dev is very active here lately :( I can't even get the library to work...
