### ISSUE TITLE
Better documentation for usage of FloatingActionMenu?

### ISSUE THREAD

**Issue by drinfernoo** [Clans/FloatingActionButton#157]
How is FloatingActionMenu used? I've added it to my layout, with FloatingActionButton children, but it doesn't show up at runtime, and there doesn't seem to be any guidance on how to actually use the classes here :(

**Comment by nsbrno** [comment]
I am also in need

**Comment by migueledgracia** [comment]
Can you guys post your layout.xml code?

**Comment by nsbrno** [comment]
The code below refers to a menu with two items.

<xml>
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical" >

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <android.support.v7.widget.Toolbar
                android:id="@+id/activity_inicio_md_toolbar_inicio"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:layout_alignParentLeft="true"
                android:background="?attr/colorPrimary"
                android:elevation="4dp"
                android:minHeight="?attr/actionBarSize"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

        </LinearLayout>



        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent" >

            <com.dexafree.materialList.view.MaterialListView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:id="@+id/activity_inicio_md_material_listview"
                app:column_count="1" />

            <com.github.clans.fab.FloatingActionMenu
                android:id="@+id/activity_inicio_md_menu_float"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_alignParentRight="true"
                android:layout_marginRight="10dp"
                android:layout_marginBottom="10dp"
                android:layout_marginLeft="10dp"
                fab:menu_fab_size="normal"
                fab:menu_showShadow="true"
                fab:menu_shadowColor="#66000000"
                fab:menu_shadowRadius="4dp"
                fab:menu_shadowXOffset="1dp"
                fab:menu_shadowYOffset="3dp"
                fab:menu_colorNormal="#3F51B5"
                fab:menu_colorPressed="#03A9F4"
                fab:menu_colorRipple="#99FFFFFF"
                fab:menu_animationDelayPerItem="50"
                fab:menu_icon="@drawable/fab_add"
                fab:menu_buttonSpacing="0dp"
                fab:menu_labels_margin="0dp"
                fab:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
                fab:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
                fab:menu_labels_paddingTop="4dp"
                fab:menu_labels_paddingRight="8dp"
                fab:menu_labels_paddingBottom="4dp"
                fab:menu_labels_paddingLeft="8dp"
                fab:menu_labels_padding="8dp"
                fab:menu_labels_textColor="#FFFFFF"
                fab:menu_labels_textSize="14sp"
                fab:menu_labels_cornerRadius="3dp"
                fab:menu_labels_colorNormal="#333333"
                fab:menu_labels_colorPressed="#444444"
                fab:menu_labels_colorRipple="#66FFFFFF"
                fab:menu_labels_showShadow="true"
                fab:menu_labels_singleLine="false"
                fab:menu_labels_ellipsize="none"
                fab:menu_labels_maxLines="-1"
                fab:menu_labels_style="@style/YourCustomLabelsStyle"
                fab:menu_labels_position="left"
                fab:menu_openDirection="up"
                fab:menu_backgroundColor="?attr/colorPrimary"
                fab:menu_fab_label="your_label_here"
                fab:menu_fab_show_animation="@anim/my_show_animation"
                fab:menu_fab_hide_animation="@anim/my_hide_animation"
                android:layout_gravity="right|bottom">

                <com.github.clans.fab.FloatingActionButton
                    android:id="@+id/activity_inicio_md_menu_item_novo_orcamento"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:src="@drawable/ic_action_view_as_list"
                    fab:fab_size="mini"
                    fab:fab_label="Novo Orçamento" />

                <com.github.clans.fab.FloatingActionButton
                    android:id="@+id/activity_inicio_md_menu_item_novo_cliente"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:src="@drawable/ic_action_view_as_list"
                    fab:fab_size="mini"
                    fab:fab_label="Novo Orçamento" />

            </com.github.clans.fab.FloatingActionMenu>

        </FrameLayout>


    </LinearLayout>



</LinearLayout>
</xml>




        
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_inicio_md);


        FloatingActionButton itemMenuNovoOrcamento = (FloatingActionButton) findViewById(R.id.activity_inicio_md_menu_item_novo_orcamento);
        FloatingActionButton itemMenuNovoCliente = (FloatingActionButton) findViewById(R.id.activity_inicio_md_menu_item_novo_cliente);

        itemMenuNovoOrcamento.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String s = v.toString();
            }
        });

**Comment by migueledgracia** [comment]
<android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:fab="http://schemas.android.com/tools"
        android:id="@+id/body"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <android.support.v7.widget.Toolbar
            android:id="@+id/activity_inicio_md_toolbar_inicio"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:layout_alignParentLeft="true"
            android:background="?attr/colorPrimary"
            android:elevation="4dp"
            android:minHeight="?attr/actionBarSize"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    </LinearLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent" >

        <com.dexafree.materialList.view.MaterialListView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/activity_inicio_md_material_listview"
            app:column_count="1" />
     </FrameLayout>

  </LinearLayout>

  <com.github.clans.fab.FloatingActionMenu
            android:id="@+id/activity_inicio_md_menu_float"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_alignParentRight="true"
            android:layout_marginRight="10dp"
            android:layout_marginBottom="10dp"
            android:layout_marginLeft="10dp"
            fab:menu_fab_size="normal"
            fab:menu_showShadow="true"
            fab:menu_shadowColor="#66000000"
            fab:menu_shadowRadius="4dp"
            fab:menu_shadowXOffset="1dp"
            fab:menu_shadowYOffset="3dp"
            fab:menu_colorNormal="#3F51B5"
            fab:menu_colorPressed="#03A9F4"
            fab:menu_colorRipple="#99FFFFFF"
            fab:menu_animationDelayPerItem="50"
            fab:menu_icon="@drawable/fab_add"
            fab:menu_buttonSpacing="0dp"
            fab:menu_labels_margin="0dp"
            fab:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
            fab:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
            fab:menu_labels_paddingTop="4dp"
            fab:menu_labels_paddingRight="8dp"
            fab:menu_labels_paddingBottom="4dp"
            fab:menu_labels_paddingLeft="8dp"
            fab:menu_labels_padding="8dp"
            fab:menu_labels_textColor="#FFFFFF"
            fab:menu_labels_textSize="14sp"
            fab:menu_labels_cornerRadius="3dp"
            fab:menu_labels_colorNormal="#333333"
            fab:menu_labels_colorPressed="#444444"
            fab:menu_labels_colorRipple="#66FFFFFF"
            fab:menu_labels_showShadow="true"
            fab:menu_labels_singleLine="false"
            fab:menu_labels_ellipsize="none"
            fab:menu_labels_maxLines="-1"
            fab:menu_labels_style="@style/YourCustomLabelsStyle"
            fab:menu_labels_position="left"
            fab:menu_openDirection="up"
            fab:menu_backgroundColor="?attr/colorPrimary"
            fab:menu_fab_label="your_label_here"
            fab:menu_fab_show_animation="@anim/my_show_animation"
            fab:menu_fab_hide_animation="@anim/my_hide_animation"
            android:layout_gravity="right|bottom">

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/activity_inicio_md_menu_item_novo_orcamento"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_action_view_as_list"
                fab:fab_size="mini"
                fab:fab_label="Novo Orçamento" />

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/activity_inicio_md_menu_item_novo_cliente"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_action_view_as_list"
                fab:fab_size="mini"
                fab:fab_label="Novo Orçamento" />

        </com.github.clans.fab.FloatingActionMenu>

</android.support.design.widget.CoordinatorLayout>

**Comment by Clans** [comment]
Work in progress: [Documentation](https://github.com/Clans/FloatingActionButton/wiki/Documentation).
