### ISSUE TITLE
FloatingActionMenu doesn't show up after being added to layout

### ISSUE THREAD

**Issue by drinfernoo** [Clans/FloatingActionButton#158]
I cannot get my FloatingActionMenu to show up in my layout at all... What am I doing wrong?

            <com.github.clans.fab.FloatingActionMenu
			android:id="@+id/time_edit_fam"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_alignParentBottom="true"
			android:layout_alignParentRight="true"
			android:layout_marginRight="8dp"
			android:layout_marginBottom="8dp"
			android:src="@drawable/ic_action_add"
			fab:menu_colorNormal="@color/colorBlueGrey"
			fab:menu_colorRipple="@color/colorRed">
			
			<com.github.clans.fab.FloatingActionButton
				android:id="@+id/btnPlus2"
				android:layout_width="wrap_content"
				android:layout_height="wrap_content"
				fab:fab_colorNormal="@color/colorOrange"
				fab:fab_colorPressed="@color/colorGreen"
				fab:fab_colorRipple="@color/colorGreenDark"
				fab:fab_shadowColor="#000"/>
			
			<com.github.clans.fab.FloatingActionButton
				android:id="@+id/btnDnf"
				android:layout_width="wrap_content"
				android:layout_height="wrap_content"
				fab:fab_colorNormal="@color/colorOrange"
				fab:fab_colorPressed="@color/colorGreen"
				fab:fab_colorRipple="@color/colorGreenDark"
				fab:fab_shadowColor="#000"/>
			
		</com.github.clans.fab.FloatingActionMenu>

**Comment by Clans** [comment]
Try changing `FloatingActionMenu`'s width and height to `match_parent`.

**Comment by drinfernoo** [comment]
That has made my FAM visible, but on opening it, the FABs show up below my other layouts.

![screenshot_20151122-083616](https://cloud.githubusercontent.com/assets/2319508/11324959/6bf1a15c-90f5-11e5-9d01-3f187c73a693.png)

**Comment by navneetht** [comment]
Create FAB in a different layout and include it in all layouts. That's what I do!
