### ISSUE TITLE
Disable Action Button

### ISSUE THREAD

**Issue by felikjunvianto** [Clans/FloatingActionButton#160]
Hi, is there a provided method or workaround to disable action button programmatically? (prevent onClickListener from being triggered if action button state is disabled, and change its button style, maybe the color to differ from enabled state)

Thanks.

**Comment by felikjunvianto** [comment]
actually nevermind, View class provide setClickable(boolean) method.

Thanks :)

**Comment by Clans** [comment]
Try `FloatingActionButton#setEnabled(false)`.

**Comment by felikjunvianto** [comment]
Work like charm. Thanks!
