### ISSUE TITLE
FloatingActionMenu not changing color

### ISSUE THREAD

**Issue by maestrolec** [Clans/FloatingActionButton#164]
Whenever I set this attribute fab:fab_colorNormal in the xml file it always defaults to red.

**Comment by jrob3rts** [comment]
I had the same issue, setting it dynamically resolved the problem.  Here is a snippet:

        final FloatingActionMenu fabMenu = (FloatingActionMenu) rlView.findViewById(R.id.fabMenu);

        fabMenu.setMenuButtonColorNormal(R.color.LightSlateGray);
        fabMenu.setMenuButtonColorPressed(R.color.LightGrey);

**Comment by BoNatali** [comment]
Hey, I had the same problem. It was apparently caused by using the wrong namespace. I solved it by changing the auto-generated namespace from  "xmlns:fab="http://schemas.android.com/tools" to xmlns:fab="http://schemas.android.com/apk/res-auto".

**Comment by joeantwi** [comment]
Hello, I tried that but still not working, any help?

**Comment by BoNatali** [comment]
Hey @joeantwi, is it just the color or all attributes you apply through the "fab" (fab:fab_size, fab:fab_icon...) prefix? Is there a way to view your xml file? It would be easier to help you that way.

**Comment by joeantwi** [comment]
Sure here is xml file:

<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:fab="http://schemas.android.com/tools"
    android:fitsSystemWindows="true"
    tools:context="dawuroapp.sankofatech.com.dawuro.MainActivity\">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="#0F97D6"
            app:popupTheme="@style/AppTheme.PopupOverlay">
            </android.support.v7.widget.Toolbar>

        </android.support.design.widget.AppBarLayout>

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.github.clans.fab.FloatingActionMenu
            android:id="@+id/menu"
            android:layout_width="303dp"
            android:layout_height="wrap_content"
            fab:menu_icon="@drawable/ic_dawurofloating"
            fab:menu_fab_size="normal"
            android:layout_gravity="right|bottom"
            fab:fab_colorNormal="#0F97D6"
            android:layout_marginRight="15dp"
            android:layout_marginBottom="15dp"
            fab:menu_showShadow="true"
            fab:menu_labels_hideAnimation="@anim/jump_to_down"
            fab:menu_labels_showAnimation="@anim/jump_from_down"
            fab:menu_labels_textColor="#FFFFFF"
            fab:menu_labels_textSize="14sp"
            fab:menu_labels_ellipsize="none"
            fab:menu_labels_maxLines="-1"
            fab:menu_labels_style="@style/MenuLabelsStyle"
            fab:menu_labels_position="top"
            fab:menu_openDirection="left"
            fab:menu_colorNormal="#DA4336"
            fab:menu_colorPressed="#E75043"
            fab:menu_colorRipple="#99FFFFFF"
            fab:menu_animationDelayPerItem="50"
            fab:menu_fab_label=""
            fab:menu_shadowColor="#66000000"
            fab:menu_shadowRadius="4dp"
            fab:menu_shadowXOffset="1dp"
            fab:menu_shadowYOffset="3dp"
            fab:menu_fab_show_animation="@anim/my_show_animation"
            fab:menu_fab_hide_animation="@anim/my_hide_animation">

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/Rptaccident"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="@dimen/fab_margin"
                android:layout_gravity="bottom|right"
                android:onClick="goReportAccident"
                app:fab_size="normal"
                app:fab_showAnimation="@anim/fab_scale_up"
                app:fab_hideAnimation="@anim/fab_scale_down"
                android:src="@drawable/ic_accident"
                app:fab_label="Report Accident"
                fab:fab_colorNormal="@color/colorPrimary"
                fab:fab_colorPressed="@color/colorPrimary"
                fab:fab_colorRipple="@color/colorPrimary"
                />

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/Rpttraffic"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="@dimen/fab_margin"
                android:onClick="goReportTraffic"
                android:layout_gravity="bottom|right"
                fab:fab_colorNormal="0F97D6"
                app:fab_size="normal"
                app:fab_showAnimation="@anim/fab_scale_up"
                app:fab_hideAnimation="@anim/fab_scale_down"
                app:fab_label="Report Traffic"
                android:src="@drawable/ic_traffic"
                />

        </com.github.clans.fab.FloatingActionMenu>
    </FrameLayout>

    </LinearLayout>


  

</android.support.design.widget.CoordinatorLayout>

**Comment by vicriese** [comment]
Hello joeantwi! Did you solve the problem? I am having the same one. Thanks!

**Comment by Adrican** [comment]
For the floating action buttons you have to use 
fab:fab_colorNormal="yourcolor"

And for the floating menu
fab:menu_colorNormal="youraccent"

As you see it changes after "fab:" with "fab" or "menu" depending on what you are editing.

**Comment by nzala** [comment]
```
<FrameLayout
    android:id="@+id/fragment_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
xmlns:fab="http://schemas.android.com/apk/res-auto">

<com.github.clans.fab.FloatingActionMenu
        android:id="@+id/menu_blue"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginRight="220dp"
        android:layout_marginBottom="10dp"
        android:layout_marginLeft="10dp"
        android:layout_marginTop="10dp"
        fab:menu_fab_size="mini"
        fab:menu_colorNormal="#1565C0"
        fab:menu_colorPressed="#2272CD"
        fab:menu_colorRipple="#62B2FF">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab14"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_star"
            style="@style/MenuButtonsSmall" />

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab24"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_star"
            style="@style/MenuButtonsSmall"
fab:fab_colorNormal="@color/colorPrimary"
            fab:fab_colorPressed="@color/colorPrimary"
            fab:fab_colorRipple="@color/colorPrimary" />

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab34"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_star"
            style="@style/MenuButtonsSmall"
fab:fab_colorNormal="@color/colorPrimary"
            fab:fab_colorPressed="@color/colorPrimary"
            fab:fab_colorRipple="@color/colorPrimary" />

 <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab34"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_star"
            style="@style/MenuButtonsSmall"
fab:fab_colorNormal="@color/colorPrimary"
            fab:fab_colorPressed="@color/colorPrimary"
            fab:fab_colorRipple="@color/colorPrimary" />

 <com.github.clans.fab.FloatingActionButton
            android:id="@+id/fab34"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_star"
            style="@style/MenuButtonsSmall"
fab:fab_colorNormal="@color/colorPrimary"
            fab:fab_colorPressed="@color/colorPrimary"
            fab:fab_colorRipple="@color/colorPrimary" />

    </com.github.clans.fab.FloatingActionMenu>

</FrameLayout>
```

**Comment by nozotrox** [comment]
@BoNatali AND @Adrican thank you so much!
