### ISSUE TITLE
FloatingActionButton elevation

### ISSUE THREAD

**Issue by devKemo** [Clans/FloatingActionButton#18]
I'm facing this issue when I put elevation to any view the floatingactionbutton always appear under that view no matter what I do.
- Without Elevation
![screen shot 2015-04-09 at 8 35 18 am](https://cloud.githubusercontent.com/assets/8436719/7061541/b4251a4a-de93-11e4-8d95-dc1d227c7913.png)
- With Elevation
![screen shot 2015-04-09 at 8 36 11 am](https://cloud.githubusercontent.com/assets/8436719/7061546/cc4fc76e-de93-11e4-8357-8c61797bb4a3.png)

**Comment by Clans** [comment]
Fixed. See the [Changelog](https://github.com/Clans/FloatingActionButton/wiki/Changelog).
