### ISSUE TITLE
Change the Floating Action Menu icon

### ISSUE THREAD

**Issue by Punchieo** [Clans/FloatingActionButton#184]
I wish there was a way to change the Floating Action Menu buttons programmatically :/

**Comment by lolsheeplol** [comment]
I'd love to have this feature as well.

**Comment by internerz** [comment]
Me too.

**Comment by Clans** [comment]
Have you guys try these: `FloatingActionButton#setImageResource()`, `FloatingActionButton#setImageDrawable()`?

**Comment by Punchieo** [comment]
I didn't realize that was an option but I would be nice to have an option where the FAM animates into another icon with the library

**Comment by Clans** [comment]
If you're talking about this animation: https://youtu.be/XngUY3PN1IQ?t=34s (the geen FAM) then you can look at this code in sample project: https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/FloatingMenusActivity.java#L161

**Comment by internerz** [comment]
`floatingActionMenu.getMenuIconView().setImageResource(R.drawable.ic_check_white_24dp);` did the trick: https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/FloatingMenusActivity.java#L181

**Comment by locofocos** [comment]
The link @Clans is dead now (the file moved). Here's the latest location for that code: [https://github.com/Clans/FloatingActionButton/blob/v1.6.4/sample/src/main/java/com/github/clans/fab/sample/MenusFragment.java#L163](url)

**Comment by mohammedhabeeb2003** [comment]
how to give orientation ?
