### ISSUE TITLE
FAB Menu with Recycler View blocks scrolling (even if menu is closed)

### ISSUE THREAD

**Issue by crymis** [Clans/FloatingActionButton#186]
My issue is, that i want a fab menu with 2 items inside (collapsing upwards on click) on a recycler view.
I added labels to the fab menu items which let the size of the needed space grow even more.

So, when the fab menu is closed, the area where the items will show in click, block my recycler view from scrolling. I have to scroll somewhere else on the screen.

**Comment by hamidrezabstn** [comment]
maybe thats because you use match_parent on layout height and weight for fab layout

**Comment by crymis** [comment]
No, I'm not.
I will just show you the main part of my xml here:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/text_color"
    android:orientation="vertical">

    <android.support.v4.widget.SwipeRefreshLayout   xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/challenge_posts_swipe_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/challenge_posts_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipToPadding="false"
            android:scrollbars="vertical" />
    </android.support.v4.widget.SwipeRefreshLayout>

    
    <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/action_upload_post_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="12dp"
        android:layout_marginRight="12dp"
        android:visibility="gone"
        fab:menu_animationDelayPerItem="40"
        fab:menu_colorNormal="@color/myPrimaryLightColor"
        fab:menu_colorPressed="@color/myPrimaryDarkColor"
        fab:menu_icon="@drawable/fab_add"
        fab:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
        fab:menu_labels_position="left"
        fab:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
        fab:menu_labels_textColor="#FFFFFF"
        fab:menu_labels_textSize="14sp"
        fab:menu_openDirection="up">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/action_take_picture_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_action_camera"
            android:visibility="gone"
            fab:fab_colorNormal="@color/myPrimaryColor"
            fab:fab_colorPressed="@color/myPrimaryDarkColor"
            fab:fab_size="mini" />
        

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/action_gallery_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_action_folder_open"
            fab:fab_colorNormal="@color/myPrimaryColor"
            fab:fab_colorPressed="@color/myPrimaryDarkColor"
            fab:fab_size="mini" />
        

    </com.github.clans.fab.FloatingActionMenu>
</RelativeLayout>


For the Fab Menu and Buttons I'm not using "match_parent".
Maybe you can give me some advise on what I need to fix.

**Comment by TurKurT656** [comment]
I think they(recycler view + fabMenu) must be inside a FrameLayout .

**Comment by crymis** [comment]
Hi, 
mhh, I tried to do that, but now I can just pull to refresh in that area (because of the swipeLayout).
So my current version is like so:

´´´XML
<RelativeLayout>
    <android.support.v4.widget.SwipeRefreshLayout>
        <FrameLayout>
            <android.support.v7.widget.RecyclerView/>
            <com.github.clans.fab.FloatingActionMenu>
                  ...
            <com.github.clans.fab.FloatingActionMenu>
        </FrameLayout>
    </<android.support.v4.widget.SwipeRefreshLayout>
</RelativeLayout>
´´´

**Comment by hamidrezabstn** [comment]
hello ! 
i've tried to reproduce your problem but i cant ! there was no problem with scrolling from where items will show after click!
here is my code : 

- MainActivity.java

```
    public class MainActivity extends AppCompatActivity {

    private RecyclerView list;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        list = (RecyclerView) findViewById(R.id.challenge_posts_recycler_view);
        list.setLayoutManager(new LinearLayoutManager(this));

        final List<String> lists = new ArrayList<>();

        for(int i=0; i<100;i++){
            lists.add("text "+i);
        }

        //list.setAdapter(new ArrayAdapter<>(this,R.layout.layout_list_item,new String[]{"salam"}));
        list.setAdapter(new RecyclerView.Adapter<RecyclerView.ViewHolder>() {
            @Override
            public HolderTest onCreateViewHolder(ViewGroup parent, int viewType) {
                final View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.layout_list_item,parent,false);

                return new HolderTest(v);
            }

            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
                ((HolderTest)holder).text.setText(lists.get(position));
            }


            @Override
            public int getItemCount() {
                return lists.size();
            }

            class HolderTest extends RecyclerView.ViewHolder {
                TextView text ;
                public HolderTest(View itemView) {
                    super(itemView);
                    text = (TextView) itemView.findViewById(R.id.text_item);
                }
            }
        });
    }
```
- activity_main.xml:

```
    <?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#fff"
    android:orientation="vertical">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/challenge_posts_swipe_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/challenge_posts_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipToPadding="false"
            android:scrollbars="vertical" />
    </android.support.v4.widget.SwipeRefreshLayout>

    <!-- Floating Action Button-Menu -->
    <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/action_upload_post_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="12dp"
        android:layout_marginRight="12dp"
        android:visibility="visible"
        fab:menu_animationDelayPerItem="40"
        fab:menu_colorNormal="#000"
        fab:menu_colorPressed="#000"
        fab:menu_icon="@drawable/fab_add"
        fab:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
        fab:menu_labels_position="left"
        fab:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
        fab:menu_labels_textColor="#FFFFFF"
        fab:menu_labels_textSize="14sp"
        fab:menu_openDirection="up">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/action_take_picture_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/fab_add"
            android:visibility="visible"
            fab:fab_colorNormal="#fef"
            fab:fab_colorPressed="#fef"
            fab:fab_size="mini" />
        <!--fab:fab_label="Take a picture"-->

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/action_gallery_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/fab_add"
            fab:fab_colorNormal="#fef"
            fab:fab_colorPressed="#fef"
            fab:fab_size="mini" />
        <!--fab:fab_label="Choose from gallery"-->

    </com.github.clans.fab.FloatingActionMenu>
</RelativeLayout>
```

- layout_list_item.xml

```
    <?xml version="1.0" encoding="utf-8"?>
<TextView
    android:id="@+id/text_item"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

</TextView>
```

BTW : its better to hide fab on Scrolling RecyclerView so it could not block view of the list items!

**Comment by TurKurT656** [comment]
change the id of recyclerView to:
android:id="@+id/list"
and check if it works or not

**Comment by crymis** [comment]
@hamidrezabstn Hey, thank you a lot for trying to help me. I also copied your code and tried that, and it was working like you said. Unfortunately it is still not working for my code, where I add card views to the recycler view. Do you think my mistake is in the item.xml code or maybe the adapter?

Heres the code for them:
*challenge_posts_item

```XML
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:id="@+id/challenge_posts_card_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="@dimen/card_vertical_margin"
    android:layout_marginLeft="@dimen/card_horizontal_margin"
    android:layout_marginRight="@dimen/card_horizontal_margin"
    android:layout_marginTop="@dimen/card_vertical_margin"
    android:orientation="vertical"
    card_view:cardCornerRadius="4dp"
    card_view:cardElevation="5dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <ImageView
                android:id="@+id/challenge_post_image"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:layout_alignTop="@+id/challenge_post_placeholderImage"
                android:layout_marginBottom="5dp"
                android:adjustViewBounds="true"
                android:maxHeight="600dp" />
        </RelativeLayout>


        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:paddingBottom="6dp"
            android:paddingLeft="@dimen/card_horizontal_padding"
            android:paddingRight="@dimen/card_horizontal_padding"
            android:paddingTop="2dp">

           ..... 
        </LinearLayout>
    </LinearLayout>
</android.support.v7.widget.CardView>
```

*ChallengePostsAdapter.java

```XML
public class ChallengePostsAdapter extends RecyclerView.Adapter<ChallengePostsAdapter.ViewHolder> {

    private ChallengePostsAdapter self = this;

    private ChallengePostsResponse mDataset;
    private Context mContext;

    private ChallengeTask mChallengeTask;


    // Provide a reference to the views for each data item
    // Complex data items may need more than one view per item, and
    // you provide access to all the views for a data item in a view holder
    public static class ViewHolder extends RecyclerView.ViewHolder {

        public View cardView;
        public ImageView imgPost;

        public ViewHolder(View view) {
            super(view);
            cardView = view.findViewById(R.id.challenge_posts_card_view);
            imgPost = (ImageView) view.findViewById(R.id.challenge_post_image);
        }
    }

    // Provide a suitable constructor
    public ChallengePostsAdapter(ChallengePostsResponse challenge) {
        mDataset = challenge;
    }

    // Create new views (invoked by the layout manager)
    @Override
    public ChallengePostsAdapter.ViewHolder onCreateViewHolder(ViewGroup parent,
                                                               int viewType) {
        // get the belonging activity context
        mContext = parent.getContext();

        // create a new view
        View v = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.challenge_posts_item, parent, false);

        ViewHolder vh = new ViewHolder(v);
        return vh;
    }

    // Replace the contents of a view (invoked by the layout manager)
    @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {
        final String imgUrl = mDataset.getPosts().get(position).getChallengePostImageMedium();
        Picasso.with(mContext).load(imgUrl).into(holder.imgPost);

        final ChallengePostResponse currentPost = mDataset.getPosts().get(position);
         ...
    }

    // Return the size of your dataset (invoked by the layout manager)
    @Override
    public int getItemCount() {
        return mDataset.getPosts().size();
    }

    // Add a list of items
    public void addAll(List<ChallengePostResponse> list) {
        mDataset.getPosts().addAll(list);
        notifyDataSetChanged();
    }

    // Clean all elements of the recycler
    public void clear() {
        mDataset.getPosts().clear();
        notifyDataSetChanged();
    }
}
```
I left a lot of code out here, because it would be too big (just some attributes that were visible on that view)

Also thanks for the advice with the hiding of the FAB Menu (I already have that on my list :smile: )


@TurKurT656 I changed the id, but nothing changed.

**Comment by XSmile2008** [comment]
Hi! I have the same problem. But I'm using Fragment with RecyclerView and FAB.
My fragment layout:
```Java
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".activity.MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <include layout="@layout/floating_action_menu"/>

</FrameLayout>
```

floating_action_menu:
```Java
<?xml version="1.0" encoding="utf-8"?>
<com.github.clans.fab.FloatingActionMenu
    android:id="@+id/fab_menu"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|end"
    android:padding="@dimen/default_padding_large"
    app:layout_behavior="com.company.wishlist.util.FloatingActionMenuBehavior"
    fab:menu_backgroundColor="@color/semi_translucent_white"
    fab:menu_colorNormal="@color/colorAccent"
    fab:menu_colorPressed="@color/colorAccentDark"
    fab:menu_icon="@drawable/ic_add_white_24dp"
    fab:menu_labels_margin="@dimen/default_padding_medium"
    fab:menu_labels_style="@style/fab_menu_labels_style"
    fab:menu_labels_textSize="@dimen/text_small"
    fab:menu_shadowColor="#37000000">

    <com.github.clans.fab.FloatingActionButton
        android:id="@+id/fab_add"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_add_white_24dp"
        app:fab_colorNormal="@color/colorAccent"
        app:fab_colorPressed="@color/colorAccentDark"
        fab:fab_label="Create new"
        fab:fab_size="mini"/>

    <com.github.clans.fab.FloatingActionButton
        android:id="@+id/fab_choose"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_book_white_24dp"
        app:fab_colorNormal="@color/colorAccent"
        app:fab_colorPressed="@color/colorAccentDark"
        fab:fab_label="Choose from existing"
        fab:fab_size="mini"/>

</com.github.clans.fab.FloatingActionMenu>
```

**Comment by XSmile2008** [comment]
So I find what cause this problem. In my code it be onClick listener for all fab_menu. It override all touches even when fab menu is closed. So if you need this listener, you need manually turn listener on when fab menu is open and turn listener off when it closed.

**Comment by yrazlik** [comment]
@XSmile2008 's solution works for me! Thanks!

**Comment by AliChaudhry8** [comment]
do this...
fam.setOnMenuButtonClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    if(fam.isOpened()){
                        //fam.close(true);

                        //fam.setVisibility(View.GONE);
                        fabT.setVisibility(View.GONE);
                        fabS.setVisibility(View.GONE);
                        fabM.setVisibility(View.GONE);
                        fabP.setVisibility(View.GONE);
                        fabB.setVisibility(View.GONE);
                        fabI.setVisibility(View.GONE);
                        fam.close(true);
                    }
                    else{
                        fam.open(true);

                       // fam.setVisibility(View.VISIBLE);
                        fabT.setVisibility(View.VISIBLE);
                        fabS.setVisibility(View.VISIBLE);
                        fabM.setVisibility(View.VISIBLE);
                        fabP.setVisibility(View.VISIBLE);
                        fabB.setVisibility(View.VISIBLE);
                        fabI.setVisibility(View.VISIBLE);
                    }

                }
            });

**Comment by saribalorhan** [comment]
You may use this: 
fabMenu.setOnMenuToggleListener(new FloatingActionMenu.OnMenuToggleListener() {

            @Override
            public void onMenuToggle(boolean opened) {
                if (opened)
                {
                 
                }
                else {
                
                }
            }
        });

for is menu opened or not
