### ISSUE TITLE
Landcape opendirection programmatically 

### ISSUE THREAD

**Issue by lucasjj85** [Clans/FloatingActionButton#188]
Is it possibile to change dinamically the opendirection when the device is in landscape mode?
 
I set the fab:menu_openDirection="up" when the device is in portrait mode but i want to change to fab:menu_openDirection="left" when the device is in landscape mode.

Any suggestion to achive this result programmatically?

Thank you

Gianluca

**Comment by Clans** [comment]
There's no such an option, sorry.
