### ISSUE TITLE
Labels are invisible when menu is initially open

### ISSUE THREAD

**Issue by osrl** [Clans/FloatingActionButton#19]
They sometimes become invisible after some redrawing (maybe something wrong with `onDraw`). Best way to reproduce is call `mFloatingActionMenu.open(true);` in `onCreate`

**Comment by Clans** [comment]
It seems like when you calling `mFloatingActionMenu.open(true)` the labels haven't been placed in the layout yet. If you want the menu to be initially opened try using `mFloatingActionMenu.open(false)` instead or if you want user to see the open animation call it after some minimal delay.

**Comment by osrl** [comment]
Sorry but `mFloatingActionMenu.open(false)` gives the same result. Delaying opening works though
