### ISSUE TITLE
FAM onTouchOutside

### ISSUE THREAD

**Issue by DenisMondon** [Clans/FloatingActionButton#192]
Hi!

I was wondering if it was possible to close the FAM if the user touches outside? (Like Hangouts for example)

Thanks
Denis

**Comment by rsd-raul** [comment]
Make both width and height match_parent on your fam and then:
```
fam.setClosedOnTouchOutside(true);
```

**Comment by DenisMondon** [comment]
Yeah I changed the height and width but I didn't see that method!! :D I'm blind ;)
Thx !
Denis
