### ISSUE TITLE
setImageDrawable 

### ISSUE THREAD

**Issue by zEuSsE** [Clans/FloatingActionButton#195]
Hi, I'm trying to dynamically set a drawable to a FloatingActionButton.
What I'm doing is:
```
myFab.setImageDrawable(myDrawable);
```
where myDrawabable is a dynamically produced drawable.
Unfortunatelly what I get is this:
![senza titolo](https://cloud.githubusercontent.com/assets/416319/12272220/898906a0-b95f-11e5-8019-c55bd62abd5f.png)
The drawable is not correctly strech to cover all the size of myFab. Do you have any idea what's the problem about?

**Comment by MirXaTouQeer** [comment]
you able to solve it yet?... if yes then let me know how? i have the same kind of problem.

**Comment by Clans** [comment]
You should use 24dp for your drawable size.
