### ISSUE TITLE
how to change fab label background color programmatically?

### ISSUE THREAD

**Issue by soban-shareviasms** [Clans/FloatingActionButton#197]

**Comment by twhit093** [comment]
You can set it like this.
``
FloatingActionButton myFAB = (FloatingActionButton) findViewById(R.id.my_fab);
myFAB.setLabelText("New Label");
``

I have observed an issue though that the shadows aren't redrawn correctly. Anyone know how to fix this?

**Comment by adeldolgov** [comment]
@twhit093 hello!I have the same problem. Did you find solution?

**Comment by twhit093** [comment]
@adeldolgov No I didn't, I ended up just adding multiple buttons and using the remove and add functions on the menu

**Comment by adeldolgov** [comment]
I found one.
I just removed shadows from label,and after this everything looks good
20 марта 2016 г. 23:50 пользователь "Tyler Whitman" <
notifications@github.com> написал:

**Comment by zdunex25** [comment]
How about **menu_labels_colorNormal** in **FloatingActionMenu**, how to change it programmatically?
