### ISSUE TITLE
fab:menu_openDirection="left"

### ISSUE THREAD

**Issue by viktorwillmann** [Clans/FloatingActionButton#198]
Can you implement fab:menu_openDirection="left? when working with low resolution devices in landscape mode it would be better to open the menu in left direction for space issues.

**Comment by kevincyh** [comment]
I am also interested in thing like this, but it would be better if it can have menu nesting and open in different direction.

**Comment by jeanvallon** [comment]
Me too ! +1

**Comment by Clans** [comment]
#46

**Comment by Ahsan221B** [comment]
Can I please have it now? It's been like 2 years!
