### ISSUE TITLE
Change `menu_labels_position` programmatically

### ISSUE THREAD

**Issue by hanihashemi** [Clans/FloatingActionButton#203]
To supporting right to left languages I need to change `FloatingActionMenu` position programmatically but `mLabelsPosition` isn't public

Thank you so much for providing this library ;)

**Comment by gregacucnik** [comment]
+1

Easiest modification would be to a do what hanihashemi suggested. But it would be best if you change attribute values for menu_labels_position to "start" and "end".

**Comment by Clans** [comment]
Same as #115

**Comment by mahmooddagga** [comment]
it would be best if you change attribute values for menu_labels_position to "start" and "end".

**Comment by mahmooddagga** [comment]
@Clans

**Comment by amorenew** [comment]
fixed here
#115
