### ISSUE TITLE
add library com.github.clans:fab:1.6.2 causes error finished with non-zero

### ISSUE THREAD

**Issue by mostafahashim** [Clans/FloatingActionButton#204]
when I added the compile 'com.github.clans:fab:1.6.2' to gradle and run the application this error shown

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_20\bin\java.exe'' finished with non-zero exit value 2
what is the problem? help please...

**Comment by ashish308515** [comment]
do you have any update on this issue, i am getting this same issue.

**Comment by mostafahashim** [comment]
yes i fixed it by add this to gradle 
defaultConfig {
        // Enabling multidex support.
        multiDexEnabled true
    }
and in myApplication class that extends application Override this finction
@Override
	protected void attachBaseContext(Context base) {
		super.attachBaseContext(base);
		MultiDex.install(this);
	}
