### ISSUE TITLE
Floating Button not floating, conflicts with FadingActionBar

### ISSUE THREAD

**Issue by mikylucky** [Clans/FloatingActionButton#205]
The floating button stays still if the FadingActionBar is used.
This is the link to the library
https://github.com/ManuelPeinado/FadingActionBar

**Comment by Rainer-Lang** [comment]
@mikylucky I don't know if it helps, but I would try this one:
https://github.com/ksoichiro/Android-ObservableScrollView

**Comment by mikylucky** [comment]
I'll try it right now, thanks! Seems awesome

**Comment by Rainer-Lang** [comment]
@mikylucky Thanks for response :)
