### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by crlang44** [Clans/FloatingActionButton#207]
Thank you Clans for supplying this awesome feature for pre-lollipop android. I have a question just about usage. I may be using it incorrectly. I included the dependency in my gradle file and included the button in my xml according to your instructions. When I build however, android studio cannot find the drawables or colors. Am I doing something wrong? Thank you and sorry I didn't know how else to contact you except on here.

**Comment by nitinjadhav** [comment]
add library folder (module) into your project and make changes in Gradle
module file.

dependencies {
> compile fileTree(dir: 'libs', include: ['*.jar'])
> compile 'com.android.support:appcompat-v7:23.0.1'
> compile 'com.android.support:recyclerview-v7:23.0.1'
> compile project(':library')
> }


On Thu, Feb 4, 2016 at 1:57 AM, Chris Lang <notifications@github.com> wrote:

> Thank you Clans for supplying this awesome feature for pre-lollipop
> android. I have a question just about usage. I may be using it incorrectly.
> I included the dependency in my gradle file and included the button in my
> xml according to your instructions. When I build however, android studio
> cannot find the drawables or colors. Am I doing something wrong? Thank you
> and sorry I didn't know how else to contact you except on here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Clans/FloatingActionButton/issues/207>.
>



-- 
Thanks & Regards ,
Nitin Jadhav

**Comment by nitinjadhav** [comment]
Hey,

 Sorry for last wrong instruction i gave it you.

You have to just copy *"Drawable"* folder from sample app into your app.
 because ic_menu and other buttons images are in that sample app drawable
folders.







On Fri, Feb 5, 2016 at 5:35 PM, Nitin Jadhav <justnitinjadhav@gmail.com>
wrote:

> add library folder (module) into your project and make changes in Gradle
> module file.
>
> dependencies {
>> compile fileTree(dir: 'libs', include: ['*.jar'])
>> compile 'com.android.support:appcompat-v7:23.0.1'
>> compile 'com.android.support:recyclerview-v7:23.0.1'
>> compile project(':library')
>> }
>
>
> On Thu, Feb 4, 2016 at 1:57 AM, Chris Lang <notifications@github.com>
> wrote:
>
>> Thank you Clans for supplying this awesome feature for pre-lollipop
>> android. I have a question just about usage. I may be using it incorrectly.
>> I included the dependency in my gradle file and included the button in my
>> xml according to your instructions. When I build however, android studio
>> cannot find the drawables or colors. Am I doing something wrong? Thank you
>> and sorry I didn't know how else to contact you except on here.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Clans/FloatingActionButton/issues/207>.
>>
>
>
>
> --
> Thanks & Regards ,
> Nitin Jadhav
>



-- 
Regards ,
Nitin Jadhav

**Comment by Clans** [comment]
Just replace them with your own colors and drawables.
