### ISSUE TITLE
How to close FAB if click outside its touch area? 

### ISSUE THREAD

**Issue by joeantwi** [Clans/FloatingActionButton#209]
Hello,

How do I close the FAB menu when I click outside of the fab icon set? Help please!!

Thanks

**Comment by RAIN102** [comment]
Take a look at the `setClosedOnTouchOutside();`

**Comment by joeantwi** [comment]
works, thanks!!

**Comment by AndroidDeveloperLB** [comment]
can this be set via an attribute?

**Comment by RAIN102** [comment]
@AndroidDeveloperLB After a quick look on the [FloatingActionButton.java](https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/java/com/github/clans/fab/FloatingActionMenu.java) and [attrs.xml](https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/res/values/attrs.xml) files, I don't think it is possible to set `setOnClosedOnTouchOutside()` via attribute.
If you can please let me know, too. 
Thank you.

**Comment by AndroidDeveloperLB** [comment]
@RAIN102 You mean it's not possible to add it, or you mean it's just not implemented?

**Comment by RAIN102** [comment]
@AndroidDeveloperLB  I mean with the current FloatingActionButton library, we don't have any xml attribute to control the `setClosedOnTouchOutside()` method.
Of course, you can fork current library and make some edits on [FloatingActionMenu.java](https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/java/com/github/clans/fab/FloatingActionMenu.java) and [attrs.xml](https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/res/values/attrs.xml) file; so then you can control the `setClosedOnTouchOutside()` via an attribute.

P/s: Editted, sorry for my bad English :)

**Comment by AndroidDeveloperLB** [comment]
Is it now fixed ?

**Comment by Clans** [comment]
Was it broken? There was the right answer to the author's question.

**Comment by AndroidDeveloperLB** [comment]
I meant if it's added.

**Comment by Clans** [comment]
The `setClosedOnTouchOutside()` is there. If you are talking about the XML attribute than no. It won't be added, at least for now.

**Comment by AndroidDeveloperLB** [comment]
Can you please consider adding it via XML attribute?

**Comment by Clans** [comment]
I guess I'll just make it `true` by default...

**Comment by AndroidDeveloperLB** [comment]
Good.
Still, I think it's better to let developers choose.

**Comment by code77se** [comment]
Would you consider opening an issue for adding setClosedOnTouchOutside as an XML attribute? Considering how configurable the library already is it seems a bit strange to leave this out.

**Comment by terranology** [comment]
Attribute setClosedOnTouchOutside doesn't work

**Comment by ravipandya412** [comment]
it works, thanks

**Comment by ravipandya412** [comment]
it works,thanks

**Comment by coskungun** [comment]
this code is working  setClosedOnTouchOutside()
 
FloatingActionMenu ffMenu = findViewById(R.id.fab_menu);
ffMenu.setClosedOnTouchOutside(true);

Thanks.

**Comment by nadafafif** [comment]
Works.. thanks a lot.. This should be added in documentation as well as its very important thing I believe.

**Comment by 50kg** [comment]
.setClosedOnTouchOutside(true) thanks!

**Comment by im-o** [comment]
@Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        if (event.getAction() == MotionEvent.ACTION_DOWN){
            if (fam_main.isOpened()){
                Rect outRect = new Rect();
                fam_main.getGlobalVisibleRect(outRect);
                if (!outRect.contains((int)event.getRawX(), (int) event.getRawY())){
                    fam_main.close(true);
                }
            }
        }
        return super.dispatchTouchEvent(event);
    }

...................
fam_main is ur FAB menu
