### ISSUE TITLE
Ability to dim background when the menu is opened

### ISSUE THREAD

**Issue by avrahamshukron** [Clans/FloatingActionButton#21]
On most apps that uses the FAB, the background is dimmed when the menu is opened. It would be nice to have this feature here.

**Comment by Clans** [comment]
Added to my TODO list. For now you can use `OnMenuToggleListener` to create such behavior by yourself.

**Comment by avrahamshukron** [comment]
Thanks!

**Comment by adek** [comment]
That would be great addition.

**Comment by HaloMediaz** [comment]
@avrahamshukron could you tell me how you dimmed the screen? The solution I tried didn't work.

 mFloatMenu.setOnMenuToggleListener(new FloatingActionMenu.OnMenuToggleListener() {
            @Override
            public void onMenuToggle(boolean opened) {
                WindowManager.LayoutParams windowManager = getActivity().getWindow().getAttributes();
                windowManager.dimAmount = 0.75f;
                getActivity().getWindow().addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);
            }
        });

I tried this code (see below), but I had no luck.

**Comment by avrahamshukron** [comment]
@HaloMediaz see this gist: https://gist.github.com/avrahamshukron/16513fe5622d11061d1e

**Comment by HaloMediaz** [comment]
@avrahamshukron Thanks!

**Comment by JaydipRadadiya** [comment]
OnMenuToggleListener work perfectly. Thanks a lot!

**Comment by Clans** [comment]
Just add the `fab:menu_backgroundColor="#ccffffff"` to the `com.github.clans.fab.FloatingActionMenu` tag. Choose the color and transparency you need.

**Comment by Gagege** [comment]
@Clans But, then you have to set the width and height of the menu to match_parent or something which makes it so you can't interact with anything "under" the menu.

**Comment by nachogarrone** [comment]
@Clans also you need to remove margins from FAB Menu. You will have a partially dimmed screen

**Comment by DanielVitsaus** [comment]
JaydipRadadiya, how did you use the OnMenuToggleListener? 
Thanks!
