### ISSUE TITLE
its not working with scrolling AppBarLayout

### ISSUE THREAD

**Issue by rchincho** [Clans/FloatingActionButton#210]
Floating action Button half disappear (height of toolbar). Its appears full in right position when toolbar gets hidden on scroll.

Main_activity.xml
CoordinatorLayout
    - AppBarLayout include toolbar
    - FrameLayout

Main_Fragment.xml
FrameLayout
    - RecycleView
    - FloatingActionButton

It works fine when I make toolbar fixed.

Please guide

**Comment by michelebombardi** [comment]
I'm experiencing a similar issue. The FloatingActionMenu works but is impossible to place it where I want using, as an example, the following attributes:
```
app:layout_anchor="@id/toolbar"
app:layout_anchorGravity="top|right|end"
```
Please fix it or tell us how to use it like Design Support Library FAB.
Thank you!

**Comment by levj220** [comment]
I too, see this issue.  I'm using an AppBarLayout with a toolbar and the menu button is half hidden.  I have attached a screenshot that shows the issue.

![selection_012](https://cloud.githubusercontent.com/assets/1356051/13386425/ecebb030-de71-11e5-84d3-9920d59d040b.png)

**Comment by Clans** [comment]
Try using the `setElevationCompat(float elevation)` method.
