### ISSUE TITLE
Tapping on a label passes the label as onClick() argument instead of the host FAB

### ISSUE THREAD

**Issue by Revenaunt** [Clans/FloatingActionButton#213]
When I set an `OnClickListener` to the FAB the label also becomes clickable. When I tap on the label, the label is the one that gets passed as the `onClick(View v)`'s View argument. In my opinion, this behavior is broken because I am not setting the listener to the label, but to the FAB itself, and, as such, I'd expect the FAB view to be the one that gets passed. Here are some logs:

When I tap the FAB:

> D/FAB onClick(): com.github.clans.fab.FloatingActionButton{3a31442f VFED..C. ...P..I. 572,746-672,854 #7f100008 app:id/fab_create_goal}

When I tap that FAB's label:

> D/FAB onClick(): com.github.clans.fab.Label{1d4d742b V.ED..C. ...P.... 398,778-572,821}

On the other hand, the code of your most recent version of the library makes me expect otherwise:

```java
public void setOnClickListener(final OnClickListener l) {
    super.setOnClickListener(l);
    mClickListener = l;
    View label = (View) getTag(R.id.fab_label);
    if (label != null) {
        label.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mClickListener != null) {
                    mClickListener.onClick(FloatingActionButton.this);
                }
           }
        });
    }
}
```

In this snippet, when the label is clicked the FAB is passed.

The version I am importing with gradle is 1.6.2. I don't know if there is an underlying bug somewhere or this snippet hasn't been shipped yet.

**Comment by AndroidDeveloperLB** [comment]
It's actually make sense. Clicking the icon should behave like clicking the label, as they are both belonging to the same item. 
This is about the same as other UI components, like tabs and action items.
