### ISSUE TITLE
Bug: ripple effect on menu labels starts from the middle when clicking the icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Clans/FloatingActionButton#218]
As the title says.
I think it's better to start the ripple from the area that the icon was pressed.

I think this could help:
http://stackoverflow.com/q/27225014/878126

**Comment by Clans** [comment]
Not a bug. It works as designed.

**Comment by AndroidDeveloperLB** [comment]
Why is it as designed? It's way far from the touch event. It should start from the touch event, just like on any other view. 
When touching a FAB, the ripple starts from the first position of the touch event. This should be done even when the touch event started on another view, and causes the ripple on themselves.
