### ISSUE TITLE
Bug: elevation doesn't seem to use the same soft shadow as on the design library FAB

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Clans/FloatingActionButton#222]
please use the same effect.

**Comment by AndroidDeveloperLB** [comment]
Why is it closed? Did you use the official FAB of the support&design library?

**Comment by Clans** [comment]
You can change the shadow as you want.

**Comment by AndroidDeveloperLB** [comment]
What to do to make it look exactly like the official FAB of the design library?
The current one doesn't seem to have the same look.
