### ISSUE TITLE
unable to implement android:scaleType="fitCenter" on FloatingActionButton

### ISSUE THREAD

**Issue by MirXaTouQeer** [Clans/FloatingActionButton#226]
unable to implement
android:scaleType="fitCenter"
### view:

`< com.github.clans.fab.FloatingActionMenu
	        android:id="@+id/fab"
	        android:layout_width="match_parent"
	        android:layout_height="match_parent"
	        android:layout_alignParentBottom="true"
	        android:layout_alignParentRight="true"
	        android:paddingRight="10dp"
	        android:paddingBottom="10dp"
	        android:paddingLeft="10dp"
	        android:tint="@color/colorPrimary"
	        fab:menu_labels_ellipsize="end"
	        fab:menu_labels_singleLine="true"
	        fab:menu_backgroundColor="#ccffffff"
	        fab:menu_colorNormal="@color/colorPrimary"
	        fab:menu_colorPressed="@color/colorPrimaryDark"
	        fab:menu_fab_label="Menu label">

	        <com.github.clans.fab.FloatingActionButton
	            android:id="@+id/fab_add"
	            android:layout_width="wrap_content"
	            android:layout_height="wrap_content"
	            android:src="@drawable/ic_edit_black"
                    android:scaleType="fitCenter"
	            android:tint="@color/colorPrimary"
				app:backgroundTint="@color/material_grey_100"
				app:elevation="6dp"
				app:pressedTranslationZ="12dp"
				fab:fab_colorNormal="@color/colorPrimary"
	        	fab:fab_colorPressed="@color/colorPrimaryDark"
	            fab:fab_size="mini"
	            fab:fab_label="Add Number" />

	        <com.github.clans.fab.FloatingActionButton
	            android:id="@+id/fab_add_call_log"
	            android:layout_width="wrap_content"
	            android:layout_height="wrap_content"
	            android:tint="@color/colorPrimary"
				app:backgroundTint="@color/material_grey_100"
				app:elevation="6dp"
				app:pressedTranslationZ="12dp"
				android:src="@drawable/ic_call_history"
				android:scaleType="fitCenter"
	            fab:fab_size="mini"
	            fab:fab_label="Add from Call Log" />

	        <com.github.clans.fab.FloatingActionButton
	            android:id="@+id/fab_add_contact"
	            android:layout_width="wrap_content"
	            android:layout_height="wrap_content"
	            android:tint="@color/colorPrimary"
				app:backgroundTint="@color/material_grey_100"
				app:pressedTranslationZ="12dp"
				android:src="@drawable/ic_contact_black"
				android:scaleType="fitCenter"
	            fab:fab_size="mini"
	            fab:fab_label="Add from Contacts" />

	    </com.github.clans.fab.FloatingActionMenu>`

![screenshot](https://cloud.githubusercontent.com/assets/13826761/13835905/2c8d7142-ec1e-11e5-9943-6d7066faffe3.png)

**Comment by Clans** [comment]
You should you 24dp icons here.
