### ISSUE TITLE
FAB with menu appears under the CardView

### ISSUE THREAD

**Issue by Kamil-H** [Clans/FloatingActionButton#228]
Hi, I've got a problem with combination of expandable FAB and CardView. After clicking on the FAB, the menu appears under the CardView, like I showed it on the screenshot:
![screen](https://cloud.githubusercontent.com/assets/11328102/13951858/98f22698-f033-11e5-9d77-1e40acc4459b.jpg)
There should be another 3 FABs under the CardView.

My layout file looks like this:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="5dp"
    android:background="@color/colorBackground">

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:cardCornerRadius="0dp"
        android:id="@+id/cv"
        >

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="200dp"
            android:padding="5dp"
            android:background="@color/colorCard">

(SOME TEXTVIEWS HERE)

        </RelativeLayout>

    </android.support.v7.widget.CardView>

    <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginRight="10dp"
        android:layout_marginBottom="10dp"
        android:layout_marginLeft="10dp"
        fab:menu_icon="@drawable/fab_add"
        fab:menu_colorNormal="@color/colorPrimary"
        fab:menu_colorPressed="@color/colorPrimaryDark"
        fab:menu_colorRipple="#99FFFFFF"
        fab:menu_labels_colorNormal="@color/colorCard">

(FABS HERE)

    </com.github.clans.fab.FloatingActionMenu>

</RelativeLayout>
```

What is a possible solution?

**Comment by joeantwi** [comment]
Did you find a solution? i'm facing the same issue

**Comment by Kamil-H** [comment]
Unfortunately no. I had to remove CardView layout.

**Comment by joeantwi** [comment]
:( -- would you be soo kind a just do a quick same or tutorial? i'm dying with this issue please :)

**Comment by fcecchi** [comment]
can't try out the source you posted, but i'll throw a guess there:

have you tried to change base layout from RelativeLayout to FrameLayout ? 

CardView itself is a FrameLayout meaning its elements will be layed on a z-index.

Using the same trick with your base layout would lead you to have the FAB layed above the cardView.

**Comment by Kamil-H** [comment]
@fcecchi thanks for response, I did it, but it didn't help.

**Comment by jorgecasariego** [comment]
@Kamil-H try changing base layout from RelativeLayout to CoordinatorLayout and in your FloatingActionMenu add android:elevation="2dp"


I show you my code so you can see if it help you

`
<android.support.design.widget.CoordinatorLayout
        android:id="@+id/root_coordinator"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.design.widget.AppBarLayout
            android:id="@+id/app_bar_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            android:fitsSystemWindows="true">

            <android.support.v7.widget.Toolbar
                android:id="@+id/app_bar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
                app:layout_collapseMode="pin"
                />

        </android.support.design.widget.AppBarLayout>

        <com.github.clans.fab.FloatingActionMenu
            android:id="@+id/menu"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentBottom="true"
            android:layout_alignParentRight="true"
            android:paddingRight="10dp"
            android:paddingBottom="10dp"
            android:paddingLeft="10dp"
            fab:menu_labels_ellipsize="end"
            fab:menu_labels_singleLine="true"
            app:menu_icon="@drawable/ic_change"
            fab:menu_backgroundColor="#ccffffff"
            fab:menu_fab_label="Options"
            app:menu_colorNormal="@color/colorAccent"
            android:elevation="2dp">

            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/fab_servicios_ocasionales"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_service"
                android:padding="5dp"
                fab:fab_size="mini"
                fab:fab_label="Services"
                app:rippleColor="@color/colorAccent"
                app:fab_colorNormal="@color/colorAccent" />

        </com.github.clans.fab.FloatingActionMenu>

        <include
            layout="@layout/content_checking_out" />

    </android.support.design.widget.CoordinatorLayout>`
