### ISSUE TITLE
Icon in FAB is blurry!

### ISSUE THREAD

**Issue by Jennykuma** [Clans/FloatingActionButton#229]
Help! 

When I add an icon through the input `fab:menu_icon="@drawable/menu"`
(`menu `is my icon name)

The button appears slightly blurry in the app.
 
![menu](https://cloud.githubusercontent.com/assets/15034854/13966769/a2410538-f039-11e5-9522-3c2ed91847b0.png)

Is there any way to fix the blurriness? My icon is 24p.
Also, how can I make my other button icons as white as the floating action menu button?

Thanks in advance!
Jenny ;)

**Comment by Jennykuma** [comment]
@Clans

**Comment by Clans** [comment]
I believe there's something wrong with your icon. As for other icons, it looks like they have some transparency.

**Comment by Jennykuma** [comment]
@clans is it because i am using a png as an icon, therefore it's blurry? I got them right from the google material icons website. would you recommend svg or another site to get icons?

**Comment by joeantwi** [comment]
Hey completely unrelated but how were you able to put the fab on top of the card view? I'm trying to do that but it goes under.

**Comment by Jennykuma** [comment]
@joeantwi 
Hey there!
I used  the `<android.support.design.widget.CoordinatorLayout>` instead of `<RelativeLayout>` or `<LinearLayout>` for my `activity_main.xml.` In there, I included all of my FAB stuff.

Then in my `content_main.xml`, which is called inside of my `activity_main.xml` file by `<include layout="@layout/content_main" />`, my recyclerview and cardview stuff are in there! :) That way, my FAB is always on top of it.

If you need some more help with it, just send me a msg

**Comment by joeantwi** [comment]
Hi Thank you, can you please share your full xml :) would love to see it and follow it please.

**Comment by AliT12345** [comment]
Hi, I'm having the same problem.  I'm using 24dp icons but they always appear blurry.  In my recyclerView I'm using the same icons and they look perfect.  However the ones in my recyclerView are higher dp and scaled down but I can't seem to do that in the floating action button.

**Comment by hiepbeos** [comment]
I having the same problem. how to fix it ?

**Comment by LunevNF** [comment]
Not fixed yet? Ohh. Why? What is the reason of this bug?
