### ISSUE TITLE
Unable to set labels to appear to the right of button 

### ISSUE THREAD

**Issue by mscosti** [Clans/FloatingActionButton#23]
The floating action menu assumes that the button will be placed on the right hand side of the screen, so the labels will appear to the left of the menu buttons. 

I want to be able to place my menu button on the far left side of the screen and still have the ability to have labels show up, which means showing them on the right side of the buttons.

Is there currently a way to do this? I tried setting the label margin to be negative, but it unfortunately cuts off the label

**Comment by Clans** [comment]
Currently, there's no way to do this. I'll add to my feature list.
