### ISSUE TITLE
I got this exception 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [Clans/FloatingActionButton#231]
Binary XML file line #80: com.github.clans.fab.FloatingActionButton cannot be cast to android.view.ViewGroup

**Comment by ch-muhammad-adil** [comment]
my bad.

**Comment by pragneshambani** [comment]
I am facing this issue. dont know how to solve it.

What did you do to fix it?

**Comment by envisiondata** [comment]
Is there a work around to this? I'm getting the same error on Xamarin Forms trying to navigate to a new page.
