### ISSUE TITLE
Hide the FAB when the menu button is clicked

### ISSUE THREAD

**Issue by shern91** [Clans/FloatingActionButton#233]
Hi, i success made the 3 menu button in FAB button based on the tutorial, but i would like to know is there possible to hide the Main FAB when the others sub menu fab is clicked.

`final FloatingActionMenu menu1 = (FloatingActionMenu) findViewById(R.id.menu1);` 

`fab1 = (FloatingActionButton) findViewById(R.id.fab1);
        fab2 = (FloatingActionButton) findViewById(R.id.fab2);
        fab3 = (FloatingActionButton) findViewById(R.id.fab3);`

meant when the fab1, fab2 or fab3 is clicked, the menu1 button will hide all the menu button, user no need to click the menu1 button for hide the others.

Thank in advance.

**Comment by kakai248** [comment]
Just do like this for every button inside the menu. You have to set the click listener anyway, just add one more line to close the menu.

```
fab1.setOnClickListener(() -> {
    menu1.close(true);
    // do what you want here
});
```

**Comment by shern91** [comment]
thank you very much, but i have done this yesterday. I think this issue is going to help the others.

**Comment by zihadrizkyef** [comment]
Hi @kakai248.. I use your code but not only the fab, the menu button is also gone, user cannot show it again.
