### ISSUE TITLE
Api 9

### ISSUE THREAD

**Issue by marbat87** [Clans/FloatingActionButton#24]
Hi,

Would it be possible to make the library compatible with API 9?
Maybe using NineOldAndroids for animation (I dind't look at the source code)?

Thanks in advance

**Comment by Clans** [comment]
Hello, 
Sorry, but no. It's an old platform and I don't want to support it.

**Comment by marbat87** [comment]
Your statement is incomplete. The complete one is: "It's an old platform that a lot of people have, and I don't want to support them".

Regards.

**Comment by sergeyfitis** [comment]
>It's an old platform that a lot of people have
Lol, today is 2015, not 2010. @marbat87 please check this https://developer.android.com/about/dashboards/index.html

**Comment by marbat87** [comment]
@sergeyfitis  And so is 6,4% negligible in your opinion? O_O try tro calculate how many people are inside 6,4%, on the total of android devices...

**Comment by sergeyfitis** [comment]
@marbat87 Issue is closed, try to calculate how many users are inside 94,6%

**Comment by marbat87** [comment]
@sergeyfitis Congratulations for the nice and clever answer. If issue is closed, you could try to shut up first next time.

Regards.

**Comment by marbat87** [comment]
@sergeyfitis  And moreover.. If 100% - 6,4% is equal to 94,6%, math si really an opinion LOL

**Comment by sergeyfitis** [comment]
@marbat87 My mistake, sorry. But it does not change the fact.
