### ISSUE TITLE
@Clans

### ISSUE THREAD

**Issue by danielevensen** [Clans/FloatingActionButton#241]
Please, contact me in regards to the FAB. My email is blessmeindeed21@gmail.com

**Comment by danielevensen** [comment]
I have a question in regards to its use in my app.

**Comment by Clans** [comment]
What is the question?

**Comment by danielevensen** [comment]
Hi,
I used the FAB in my app, adapted slightly. I apologize I appreciate your time. This is what I have put in my apps about page for the Apache License. Is this correct.
I used android-floating-action-button library by Dmytro Tarianyk as a base for development for the FAB only.https://github.com/ClansApache License
Then the actual license.
 Version 2.0, January 2004 http://www.apache.org/licenses
Daniel Evensen

**Comment by Clans** [comment]
That's ok.
