### ISSUE TITLE
Floating Action Button is not floating

### ISSUE THREAD

**Issue by toSilence** [Clans/FloatingActionButton#247]
In the screenshot you see a customized view element (editor with yellow background) which should be overlayed when the menu opens.

Unfortunately its not overlayed because by default the floating action button is using that size - which it would need when the menu expands.

![newfloatingclose](https://cloud.githubusercontent.com/assets/2422649/14710865/76ba7ca4-07d7-11e6-931f-b9620903abae.png)
![newfloatingopen](https://cloud.githubusercontent.com/assets/2422649/14710864/76b4761a-07d7-11e6-810d-7b1e8cf178b0.png)

**Comment by Clans** [comment]
Please post your code here.

**Comment by toSilence** [comment]
Hi Clans
I solved it already ;-)
Thanks for the quick response.

The problem was I was drawing my custom view with a height of 0dp.
Because the size is detected and then set dynamically.
I set android:layout_height="fill_parent" and its working.
