### ISSUE TITLE
Make the background of Float Action Menu appears over AppBarLayout

### ISSUE THREAD

**Issue by brunoNmelo** [Clans/FloatingActionButton#249]
Hey everyone,
I noticed that when a implemente the FloatActionMenu on a CoordinatorLayout the background is not overlapping the AppBarLayout, but this only happens on devices with API > 21.
How do I make the background overlap everything, including the Toolbar inside AppBarLayout?

In the image below, the left side is the application running on API 16 device, and the right side is running on api 21. The background of Float Action Menu overlaps the toolbar on device with api < 21.

![captura de tela 2016-04-23 12 05 30](https://cloud.githubusercontent.com/assets/14285854/14762235/e0c92a80-094b-11e6-9977-a3541276daa9.png)

**Comment by Clans** [comment]
Try to set `android:elevation="8"` to the `FloatingActionMenu`.

**Comment by brunoNmelo** [comment]
Thank you very much.
It totally worked.
I think you should consider implementing this elevation by default since that is the default behavior on devices with Api < 19, only a suggestion.

**Comment by dawidhyzy** [comment]
This doesn't work with CollapsingToolbarLayout

**Comment by kevinhinterlong** [comment]
I recently tried to do this as well and it did not work with an elevation level below 12:
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            floatingActionMenu.setElevation(12);
        }
```
