### ISSUE TITLE
FloatingActionMenu does not expand

### ISSUE THREAD

**Issue by sciencepro** [Clans/FloatingActionButton#25]
I have a FloatingActionMenu in a Fragment.  In some cases, the menu does not expand.  Typically causing this fragment to be recreated resolves the issue.

For what it's worth, the OnClick listeners for the FloatingActionButtons inside the FloatingActionMenu always trigger reliably once the menu is showing.

Any tips on how to troubleshoot this?

**Comment by Clans** [comment]
Could you provide your xml and fragment code?

**Comment by sciencepro** [comment]
http://pastebin.com/RCiUhaCC
http://pastebin.com/C37muEGw

A lot of irrelevant code in there, but I left it all in. I'm not doing much with the FABs besides setting OnClick listeners with Butterknife (line 102-114).  Those always work.  It's the expansion of the FloatingActionMenu that is unreliable.

**Comment by Clans** [comment]
Sorry, can't even imagine what can be wrong. I've tried your layout without some views that I don't have in my dependencies  and everything works fine for me.

**Comment by sciencepro** [comment]
Thanks for checking it out.  I'll keep playing with it and see if I can pin down exactly what steps will reproduce the issue.

**Comment by sciencepro** [comment]
I have a theory about the cause of this - in some circumstances, I show a view on top of the region occupied by the FAB, and then set its visibility to 'gone.'  I've noticed that only the area that was never covered by this other view responds to a click. Does this sound like a plausible cause, and can you think of any possible fixes?

**Comment by kleiren** [comment]
(I don't know is this has been answered yet)
It seems that the FAM (Floating Action menu) wont expand if there is anything "clickable" below it. I've had this problem with an "EditText" below the area where the button apears. When moved the editText to other position the FAM worked perfectly.

So, the solution that worked for me is moving any clickable items from the area where the FAM appears.
