### ISSUE TITLE
FAB like hangouts app

### ISSUE THREAD

**Issue by tarolechaitanya** [Clans/FloatingActionButton#259]
Hi !!! I would like to have hangout app like FAB and with support for API 8 as well
Can you provide solution or guide me in right direction
Thanks
![fab](https://cloud.githubusercontent.com/assets/14307698/15040755/ad4c143c-12d4-11e6-9578-ba601753c0f6.png)

**Comment by Clans** [comment]
Fork it and rewrite the code to make it work on API 8.
