### ISSUE TITLE
FAB labels are gone after switching the tab.

### ISSUE THREAD

**Issue by domino-bs** [Clans/FloatingActionButton#26]
I have placed 3 FABS (in FabMenu) with labels in a tab view (middle tab of 3 tab pages). If I open the FabMenu, swipe to another tab and after that swipe back to the screen with the FABS then the open FabMenu with the 3 FABS is stll there (as expected) but the labels are gone. After clicking the FabMenu button to close the Menu the labels are suddenly been shown and the menu closes.
It seems to me that the FAB-Labels are cleared in this moment the tab view is redrawn (after swiping back)!? Any ideas?

**Comment by Clans** [comment]
I'll inspect this as soon as I'll have time. For now you can try to **close** the menu when switching **from** this tab and **open** it when switching **to** this tab. Use `close(false)` and `open(false)` methods without animation.

**Comment by Clans** [comment]
Are you using a ViewPager?

**Comment by domino-bs** [comment]
Yes I am using a support v4 viewpager.

**Comment by domino-bs** [comment]
I tried your workaround and it helps! I overrided the "public void setUserVisibleHint(boolean isVisibleToUser)"-Method which notifies the fragment about being shown to the user. In this case I use "close(false)" now and everything is fine. Do you want me to keep this issue open so you can add more details about the original issue or should I close the issue because there is a workaround for now?

Many thanks for your work on this library and your comments in this issue!

**Comment by Clans** [comment]
Yes, let it be opened for now.
