### ISSUE TITLE
Get the view of the floating action menu

### ISSUE THREAD

**Issue by Arathus** [Clans/FloatingActionButton#267]
Hello :)

First of all I want to give you a big thanks for this library. 

I want to get the view of the floating action menu's icon. Not to the whole view, just the floating action menu's view.

Can I do it somehow ?

**Comment by Clans** [comment]
Not sure I understand what you're talking about...
`getMenuIconView()` will return you the `ImageView` that is used inside the `FloatingActionMenu`'s button. Is that what you're asking for?

**Comment by Arathus** [comment]
Oh thanks ;)
Not this is what I looking for, but it is also good... ;)
Thank you ;)
