### ISSUE TITLE
Auto close FloatingActionMenu when FloatingActionButton got clicked

### ISSUE THREAD

**Issue by ramabmtr** [Clans/FloatingActionButton#27]
Can you make FAM close automatically when FAB inside it (child of FAM) got clicked?

**Comment by Clans** [comment]
Hi,
I believe there could be some cases which don't need such behavior as default. Also, you can achieve desired behavior by adding only one line of code.

**Comment by ramabmtr** [comment]
Yeah, I already do that, but it will be cool that we can set it via XML like fab:menu_autoClose="true/false".

btw, thanks for great library.

**Comment by mus9876** [comment]
it may help others:-

        /*Auto Close => if the user doesn't make a choice */
        fabMenu.setOnMenuToggleListener(new FloatingActionMenu.OnMenuToggleListener() {
            @Override
            public void onMenuToggle(boolean opened) {
                if (opened){
                    new Handler().postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            fabMenu.close(true);
                        }
                    },3000);
                }
            }
        });
