### ISSUE TITLE
Changing FloatingActionMenu icon by code

### ISSUE THREAD

**Issue by savasozturk** [Clans/FloatingActionButton#271]
Is it possible to change FloatingActionMenu menu_icon by code dynamically? Thanks in advance

**Comment by Clans** [comment]
There's an [article](https://github.com/Clans/FloatingActionButton/wiki/Documentation#use-different-icons-for-closed-and-opened-menu) for that in the Documentation. ;)

**Comment by Rahman-94** [comment]
i still don't understand how to change the FloatingActionMenu icon!

**Comment by Pazza** [comment]
You need to set the icon directly on the menu's image view.
`mFloatingActionMenu.getMenuIconView().setBitmap(myBitmap)`
