### ISSUE TITLE
Allow long press on the Floating action menu to permit other actions

### ISSUE THREAD

**Issue by koolkvd** [Clans/FloatingActionButton#276]
Hi Clans,

I need to use the Floating action menu button for muliple purposes. Can i use your overriden onTouchEvent code and add a part for handling long clicks? will it cause issues?

**Comment by koolkvd** [comment]
My Bad,

You have already given an option to add a listener for long clicks programmaticaly,
setOnMenuButtonLongClickListener

Should i use this to set a View.onLongClickListener object on the action_menu?

**Comment by koolkvd** [comment]
My Bad,

You have already given an option to add a listener for long clicks programmaticaly,
setOnMenuButtonLongClickListener

Should i use this to set a View.onLongClickListener object on the action_menu?

**Comment by dtarianyk** [comment]
Yes. :)

**Comment by Clans** [comment]
Yes. :)
