### ISSUE TITLE
Cannot change FAB Menu Icon color

### ISSUE THREAD

**Issue by akherbst2** [Clans/FloatingActionButton#277]
I've tried all sorts of ways but I can't seem to change the color of the FAB menu icon.  I would like my FAB menu button to be white, but that means that the plus sign is hard to see.  Any way to get around this?
![capture](https://cloud.githubusercontent.com/assets/16625021/16134869/c5aa3c9a-33ed-11e6-8778-a9d29c162c48.PNG)

**Comment by akherbst2** [comment]
Sidenote-- I used my own vector drawable for the top icon, so I was able to change the color manually.  The plus sign was built in, so I couldn't figure out how to change it.

**Comment by akherbst2** [comment]
SOLUTION:  I created my own icon using vector drawables, and manually set the color inside the vector file.  The plus sign still swings open like it did before!

![image](https://cloud.githubusercontent.com/assets/16625021/16153479/80cca194-3474-11e6-8730-aa3b9ff5d332.png)
![image](https://cloud.githubusercontent.com/assets/16625021/16153495/8f6abb50-3474-11e6-8eda-8f0cd0375100.png)

**Comment by hendrawd** [comment]
actually you can directly set color filter to the image view like this
```
FloatingActionMenu fam = (FloatingActionMenu) findViewById(R.id.fam_id);
int colorThatYourWant = Color.BLACK;
fam.getMenuIconView().setColorFilter(colorThatYourWant);
```

**Comment by AbdAllahBoda** [comment]
@hendrawd do you have any idea of haw to do the same with the icons of the buttons too?, that would be great :)
