### ISSUE TITLE
how to auto close floating menu when user tap anywhere on screen

### ISSUE THREAD

**Issue by sumitkvijay** [Clans/FloatingActionButton#278]
Is there any way to close the expanded floating menu if user tap anywhere on the screen except the floating menu. By default, if closed only when user tap on the Close icon on the floating menu,

**Comment by dtarianyk** [comment]
Please use `FloatingActionMenu#setClosedOnTouchOutside(true)`.

**Comment by Clans** [comment]
Please use `FloatingActionMenu#setClosedOnTouchOutside(true)`.

**Comment by sumitkvijay** [comment]
Sorry, but I am beginner. Can you please explain how and where to use this condition?

**Comment by Clans** [comment]
In your `Activity`'s `onCreate()` method:
```Java
FloatingActionMenu myMenu = (FloatingActionMenu) findViewById(R.id.my_menu);
myMenu.setClosedOnTouchOutside(true);
```

**Comment by sumitkvijay** [comment]
Thanks a lot 👍

**Comment by dmsherazi** [comment]
Tried this but did not work

**Comment by Fuhrmann** [comment]
@dmsherazi see https://github.com/Clans/FloatingActionButton/issues/192

**Comment by mus9876** [comment]
@dmsherazi 
Do something like that:- 

`<com.github.clans.fab.FloatingActionMenu
        android:id="@+id/fab_menu"
        android:layout_width="match_parent"
        android:layout_height="match_parent"`
