### ISSUE TITLE
FloatingActionButton is not changing colour

### ISSUE THREAD

**Issue by comeondude** [Clans/FloatingActionButton#279]
I'm facing trouble with changing the color of the FloatingActionButton inside a FloatingActionMenu. I tried putting <code>fab:manu_colorNormal</code> as a property of the FloatingActionButton, but it seems it has no effect and showing the default colour.

Here's the layout I'm using. Note that, I've used <code>xmlns:fab="http://schemas.android.com/apk/res-auto"</code>. It was suggested somewhere to check if the <code>xmlns:fab</code> is pointed to <code>apk/res-auto</code>. I set that properly, but yet no luck.

``` java
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:background="@color/background">

    <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/fab_menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="10dp"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"
        fab:menu_colorNormal="@color/fab_close_background"
        fab:menu_colorPressed="@color/fab_close_background_pressed"
        fab:menu_colorRipple="@color/fab_close_background_ripple">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/menu_delete"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_delete_white_24dp"
            fab:fab_size="mini"
            fab:menu_colorNormal="@color/fab_delete_background"
            fab:menu_colorPressed="@color/fab_delete_background_pressed"
            fab:menu_colorRipple="@color/fab_delete_background_ripple" />

    </com.github.clans.fab.FloatingActionMenu>

</RelativeLayout>
```

**Note:** I could change the colour of the FloatingActionMenu button successfully. menu_colorNormal works perfectly for the close button in my layout.

Here's how it looks like in my application. Red is the default colour which I'm trying to change.
![FloatingActionButton inside FloatingActionMenu](http://i.imgur.com/hiTpC3k.png?1)

**Comment by umesh-kushwaha** [comment]
replace fab:menu_colorNormal to fab:fab_colorNormal in FloatingActionButton

fab:menu_colorNormal is used to set the color of menu icon and fab:fab_colorNormal is used to set the color of floating action button. Now your floatingaction button property will be 

<com.github.clans.fab.FloatingActionButton
            android:id="@+id/menu_delete"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_delete_white_24dp"
            fab:fab_size="mini"
            fab:fab_colorNormal="@color/fab_delete_background"
            fab:fab_colorPressed="@color/fab_delete_background_pressed"
            fab:fab_colorRipple="@color/fab_delete_background_ripple" />

Try sample app.

**Comment by comeondude** [comment]
Thanks. Its working. 👍

**Comment by prashantsinghpaliwal** [comment]
Unable to customize colors. Has done everything. Even in design pane, it shows the green color but the app when installed , shows same default red color. Please help!!

**Comment by ganeshkumar10** [comment]
umesh-kushwaha
 Thanks its working fine

**Comment by AhtishamSagheer** [comment]
Thanks

**Comment by titosobabas** [comment]
Thank you, this worked for me
