### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by doc-rj** [Clans/FloatingActionButton#28]
Hi,

No issue here. Just dropping a note to say I used your library in this project:
https://github.com/doc-rj/smartcard-reader

Without much trouble, I was able to make it look and feel like the Google Keep menu experience.

Thanks for the great work. I plan to add a thanks/credits section to my README soon.

Thanks,
-- Ryan

**Comment by doc-rj** [comment]
By the way, I already have a couple of screenshots in the README, and will add the credits.

**Comment by Clans** [comment]
Good to know that my work is helpful. Thank you.
