### ISSUE TITLE
[QUESTIONS]

### ISSUE THREAD

**Issue by priyank-purohit** [Clans/FloatingActionButton#285]
How do I allow users to close the menu by tapping in the white space? Is it already a feature that I can't find?

How do I change the button colour when the menu is open? I want to change the cancel/dismiss button's background from the normal red to gray.

I might just contribute if those two features don't exist yet! :+1:

**Comment by Clans** [comment]
1. Use `FloatingActionMenu#setClosedOnTouchOutside(true)`.
2. Use `FloatingActionMenu#setMenuButtonColorNormal(int color)` or `FloatingActionMenu#setMenuButtonColorNormalResId(int colorResId)`.

**Comment by priyank-purohit** [comment]
Thanks! That worked perfectly. For the 2nd issue, I wrote the following code for changing the dismiss button colour:

```
public FloatingActionMenu fabMenu;
fabMenu = null; // get it!

fabMenu.setOnMenuToggleListener(new FloatingActionMenu.OnMenuToggleListener() {
            @Override
            public void onMenuToggle(boolean opened) {
                Log.d("FAB", "Floater is toggling...!");
                if (fabMenu.isOpened()) {
                    fabMenu.setMenuButtonColorNormalResId(R.color.colorWhite);
                    Log.d("FAB", "Setting to white");
                }
                else {
                    fabMenu.setMenuButtonColorNormalResId(R.color.colorRed);
                    Log.d("FAB", "Setting to red");
                }
            }
        });
```

I couldn't use `.setMenuButtonColorNormal()` for this, for some reason.
