### ISSUE TITLE
project build fail fail~~TipsCould not find property 'VERSION_CODE' on project ':library'.

### ISSUE THREAD

**Issue by ikkyu0319** [Clans/FloatingActionButton#29]
versionCode Integer.parseInt(project.VERSION_CODE)
        versionName project.VERSION_NAME

wheres project.xxxx~~

**Comment by Clans** [comment]
Are you trying to build the sample project?

**Comment by jdzuri** [comment]
I had the same problem and have solved establishing real values:

<pre>
versionCode 150
versionName "1.5.0"
</pre>

and removing the next line of library build.gradle:

<pre>
apply from: '../gradle-mvn-push.gradle'
</pre>
