### ISSUE TITLE
Support Android Iconic

### ISSUE THREAD

**Issue by SAFatemi** [Clans/FloatingActionButton#298]
Salam.
It's good to use Android Iconic for icons.
https://github.com/mikepenz/Android-Iconics

**Comment by mikepenz** [comment]
@SAFatemi as maintainer of the `Android-Iconics` library I must admit that I don't really see the requirement of adding native `Android-Iconics` support to this library, as it will only bring another dependency, and for people who don't need the iconics that's unnecessary (even if the iconics core is tiny)

To go a bit deeper. This library already features `Android-Iconics` support as the FAB is based on the `ImageButton` (https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/java/com/github/clans/fab/FloatingActionButton.java#L39)  which already has native `Android-Iconics` support via the custom `LayoutInflater` support of the `Android-Iconics` project. [See more here.](https://github.com/mikepenz/Android-Iconics#3-define-iconicslayoutinflater-to-enable-automatic-xml-icons-detection-optional) and [here](https://github.com/mikepenz/Android-Iconics#as-imageview-only-available-if-you-follow-step-3-or-inject-the-context) (`ImageButton` extends `TextView`)

And if you want programatical support. Just create a normal `IconicsDrawable` and pass it as `Drawable` (which the lib would simply do anyway)

**Comment by SAFatemi** [comment]
@mikepenz Salam.
Thank you very much for your answer and for your well support .
Good luck.
