### ISSUE TITLE
How to use with RecyclerView?

### ISSUE THREAD

**Issue by Rainer-Lang** [Clans/FloatingActionButton#3]
Please add an example for usage with a RecyclerView.
Thanks.

**Comment by Clans** [comment]
Added a basic example for usage with RecyclerView.
Please see https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/RecyclerViewActivity.java

**Comment by Rainer-Lang** [comment]
Thanks

**Comment by Alim910** [comment]
The link is not working
