### ISSUE TITLE
Ripple Effect/Pressed Effect Not Working

### ISSUE THREAD

**Issue by AkshayPathak** [Clans/FloatingActionButton#30]
Hi!

Thanks for the great library, but when I implemented it and tested it out, the color does not change when clicked nor does the ripple effect show. 

I added the Grade dependency and then added the floating action button to the activity_main.xml. Do I need to add Java code to make the ripple effect and the pressed effect to work?

Sorry if my mistake is very basic. Still a beginner to Android :)
Thank you so much for your help and thanks again for the amazing library!

This is the xml that I have for the FAB.

     <com.github.clans.fab.FloatingActionButton
             android:id="@+id/fab"
             android:layout_width="wrap_content"
             android:layout_height="wrap_content"
             android:layout_alignParentBottom="true"
             android:layout_alignParentRight="true"
             android:src="@drawable/fab_plus_icon"
             fab:fab_colorNormal="@color/fab_material_red_500"
             fab:fab_colorPressed="@color/fab_material_red_900"
             fab:fab_colorRipple="#D32F2F"
             fab:fab_size="normal"
             fab:fab_elevationCompat="4dp"
             />

**Comment by Clans** [comment]
Hello,
Have you set the OnClickListener for the FloatingActionButton?

**Comment by AkshayPathak** [comment]
Thanks a lot, it worked after I set the OnClickListener! Thanks
