### ISSUE TITLE
Click On FloatingActionButton Falls Through to RecyclerView Item

### ISSUE THREAD

**Issue by rbrinson** [Clans/FloatingActionButton#31]
I'm trying to utilize your library (thank you, BTW) to create a floating action button to initialize adding items to a RecyclerView. The floating action button does show up on the screen above the RecyclerView in the bottom right. However, clicking on the button causes a ripple effect on the RecyclerView item beneath the button and causes the item view activity to launch. It's as if the floating action button does not exist on the screen, even though it is clearly seen. I had a similar issue with the option list in my Navigation Drawer and resolved it by adding android:clickable="true" to the layout resource file. However, that does not seem to be helping in this case. Below is my layout XML file. Do you see anything that would cause an issue with the FloatingActionButton library?

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/person_list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical" />

    <com.github.clans.fab.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginBottom="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginEnd="8dp"
        android:src="@drawable/fab_add"
        android:clickable="true"
        fab:fab_colorNormal="@color/colorAccent"
        fab:fab_colorPressed="@color/colorAccentDark" />

</RelativeLayout>
```

**Comment by Clans** [comment]
Have you set the OnClickListener to the FloatingActionButton?

**Comment by rbrinson** [comment]
Thank you Clans for your response. I had not set an OnClickListener as I was simply trying to set a FAB on the fragment and get a sense for how it would work and how it would look. I assumed that without an OnClickListener it would just behave like a button with no associated events. As a quick test, I set the OnClickListener for the FAB to display Toast, and now clicking the FAB does respond with the pressed color change, ripple effect, and, of course, the Toast message is displayed. I will close this issue. Thank you again!
