### ISSUE TITLE
Vector Drawables Support

### ISSUE THREAD

**Issue by RafaAtrixDevelopers** [Clans/FloatingActionButton#348]
![image](https://cloud.githubusercontent.com/assets/23501342/21103472/c2b48e7e-c069-11e6-9017-7392b3b2c9d5.png)

When using VectorDrawableCompat, you need to use app:srcCompat

When I put the app:srcCompat the icon does not appear

and with android:src the android:tint to change icon color does not work

**Comment by Tadly** [comment]
sounds like a dup of #262
