### ISSUE TITLE
Fab label shadow size

### ISSUE THREAD

**Issue by jeffersonlicet** [Clans/FloatingActionButton#349]
if you change the fab label text dynamically the label shadow does not change its size. Is there any method to update te label layout?

Thank you.

**Comment by sdelaysam** [comment]
@jeffersonlicet please consider this PR https://github.com/Clans/FloatingActionButton/pull/397  
don't know if this repo is maintained or somebody is going to merge it

**Comment by jeffersonlicet** [comment]
Thank you.
