### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by crysan** [Clans/FloatingActionButton#35]
Hi!
How do I know the status menu of the currently open or closed?

**Comment by Clans** [comment]
Hello,
Try to use the `FloatingActionMenu#OnMenuToggleListener()`.

**Comment by crysan** [comment]
It's a bit wrong. I need to close the open menu by pressing the Back button on the device. For this you need to know the status menu: open or closed.

**Comment by Clans** [comment]
Use a global variable to keep the status from the `OnMenuToggleListener()`.

**Comment by crysan** [comment]
Exactly! As I did not know? Thank you!

**Comment by Clans** [comment]
Also there is a method `FloatingActionMenu#isOpened()`. Is that what you need?

**Comment by ChristopheVersieux** [comment]
That's very easy:    

@Override
    public void onBackPressed() {
        if (fabMenu != null & fabMenu.isOpened()) {
            fabMenu.close(true);
        } else {
            super.onBackPressed();
        }
    }

**Comment by crysan** [comment]
Yes, I did. Thank you!
