### ISSUE TITLE
Fab click behavior enhancement.

### ISSUE THREAD

**Issue by Kinnonii** [Clans/FloatingActionButton#36]
Hi!
I think you should specify that if the FAB doesn't have an OnClickListener, it won't even respond and the view under it will be clicked, leading to 'think' it's a bug, because it doesn't change its state to pressed.

For example: I put a FAB with a RecyclerView, and if I don't set an OnClickListener, the row under the button can be pressed. In my case, just for test how it behaves.

Maybe a default empty OnClickListener on the FAB would help! Thanks!

**Comment by Clans** [comment]
Will be added in next release.

**Comment by Kinnonii** [comment]
Thank you :)
