### ISSUE TITLE
Add button programmatically?

### ISSUE THREAD

**Issue by jasonni** [Clans/FloatingActionButton#37]
Hi,
May I ask is there have any way to add button programmatically?
thanks.

**Comment by pawelByszewski** [comment]
It is not a problem to add single button, you just have to inflate view.
But there is a problem if you would like to add FAB menu with dynamicly created buttons. I am trying to create menu in that way but without success.

**Comment by DavideSteduto** [comment]
Also, how to change Icon in the menu button at runtime?
I've added this, is it enough?

	public void setMenuIconView(Drawable drawable) {
		if (mIcon != drawable) {
			mIcon = drawable;
			mImageToggle.setImageDrawable(mIcon);
		}
	}

**Comment by Clans** [comment]
Yup, that should be enough. Also you can use the `setImageResource(int resId)` method.

**Comment by DavideSteduto** [comment]
Ok, but it seems there's a problem of scaling the image (I generate it on the fly from SVG with 24dp and no problem on others custom views), but after I set it, on devices API >= 16 is not visible while on API 14 the image is little, any idea?

**Comment by jasonni** [comment]
Dear Clans, 
I had used the v1.5.0, it's awesome and solve my problem, 
thanks a lot :+1:

**Comment by Frykky** [comment]
what is the way to add menu AND button programmatically in 1.5.0?

**Comment by Clans** [comment]
You need to set the OnClickListener after you've added the button to the menu, because before that the OnClickListener doesn't know anything about the label of the button.

**Comment by gang018** [comment]
guys, can you provide some code how to create menu programmatically?
