### ISSUE TITLE
fab:menu_openDirection="up" - ERROR

### ISSUE THREAD

**Issue by ingpeternemec** [Clans/FloatingActionButton#42]
Very nice library, thanks. 
But when I add 
fab:menu_openDirection="up"
to XML layout definition,  an error occurs
Error:(25) No resource identifier found for attribute 'menu_openDirection' in package ....

I would like open menu from right to left
Can you help me please?

**Comment by Clans** [comment]
There is no such option to open the menu from right to left. Only vertical directions.

**Comment by ingpeternemec** [comment]
That is a pity :-(

**Comment by Shajeel-Afzal** [comment]
Hi @Clans!

Can you please tell me how can i open the menu in down direction. Actually i am also facing the same problem when i add 

ab:menu_openDirection="up"

to XML layout definition, an error occurs
Error:(25) No resource identifier found for attribute 'menu_openDirection' in package ....

Thanks.

**Comment by Shajeel-Afzal** [comment]
@Clans kindly please guide on this.

**Comment by Clans** [comment]
I can't see the issue. Try clean and rebuild the project.

**Comment by Shajeel-Afzal** [comment]
Thanks issue is resolved. Is there any plan to bring it back to API level 9?

On Sun, Jun 14, 2015 at 3:11 PM, Dmitry Tarianyk <notifications@github.com>
wrote:

> I can't see the issue. Try clean and rebuild the project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Clans/FloatingActionButton/issues/42#issuecomment-111809438>
> .
>



-- 

*Shajeel  Afzal*
Call: +923003419643 | Skype: shajeel.voice
<http://pk.linkedin.com/in/shajeelafzal/>
<http://facebook.com/shajeel.afzal>
<https://plus.google.com/+shajeelafzal/> [image: enter image description
here] <https://twitter.com/ShajeelAfzal>

**Comment by Clans** [comment]
Sorry, but no.

**Comment by Nishanthbabu** [comment]
menu_openDirection is not geving me menu from bottom...

**Comment by SethC94** [comment]
Sorry to open up old thread, but is there still no option fab:menu_openDirection="left/right" ???
It would be so much more aesthetically pleasing 

also..
Im having issues getting your clans fab to display on top of my RecyclerView

Thanks for any help
