### ISSUE TITLE
View behind the FloatingActionMenu is not clickable|scrollable

### ISSUE THREAD

**Issue by ghost** [Clans/FloatingActionButton#423]
DETAILS - I have placed FloatingActionMenu over RecyclerView, I have set the width and height of FloatingActionMenu both to wrap_content, I have 2 FloatingActionButton inside FloatingActionMenu.

PROBLEM- The area behind the FloatingActionMenu is not scrollable due to which I'm unable to scroll my RecyclerView from the area covered by FloatingActionMenu.

**Comment by droidwithme** [comment]
Why this is issue is closed while there is no solution provided?
