### ISSUE TITLE
Floating Action Menu always opens upwards

### ISSUE THREAD

**Issue by PogopunkXIII** [Clans/FloatingActionButton#439]
I took the downward Floating Action Menu form the sample and dropped it in my project and can't seem to get it to expand downwards, no matter what I do it it always expands upwards.

In the layout design page it displays the FAM as if it's going to expand downwards, but when running on the emulator the FAM button moves down to the middle of the screen and when pressed the FABs expand up.

I definitely have the `fab:menu_openDirection="down"`

**Comment by codeForge13** [comment]
can you show the xml?

**Comment by Golden-Slumber** [comment]
try this:  xmlns:fab="http://schemas.android.com/apk/res-auto"

**Comment by PogopunkXIII** [comment]
https://github.com/PogopunkXIII/GHCharacterTracker/blob/uiUpdate/app/src/main/res/layout/character_sheet_2.xml#L9

This is a link to where I'm trying to use the floating Action Menu

**Comment by Golden-Slumber** [comment]
I have met the same problem before.  just change  xmlns:fab="http://schemas.android.com/tools"  to 
 xmlns:fab="http://schemas.android.com/apk/res-auto"

**Comment by PogopunkXIII** [comment]
@Golden-Slumber You're the man. That worked perfectly! Thanks.
