### ISSUE TITLE
Support for AddMenuButton at index

### ISSUE THREAD

**Issue by aalap-shah** [Clans/FloatingActionButton#44]
Hey, 
Thank you so much for your library. Its Awesome. Just wanted to request for a feature where user can choose the index at which he wants to add FAB. Basically I have a use-case similar to Inbox, 1 FAM and few xml defined FAB inside it, and few programmatically added at runtime. Now the newly added FAB always appear at the bottom. But I wanted them to appear above my pre-defined FABs.

**Comment by Rainer-Lang** [comment]
+1

**Comment by aalap-shah** [comment]
Thank you :)
