### ISSUE TITLE
Do not make Menu Button animate

### ISSUE THREAD

**Issue by whowazit** [Clans/FloatingActionButton#54]
I don't want to animate the menu button

**Comment by Clans** [comment]
Have you tried `FloatingMenuButton.setIconAnimated(false)`?

**Comment by whowazit** [comment]
Yes..it still rotates..

**Comment by Clans** [comment]
Please see the blue menu button in the sample project.

**Comment by whowazit** [comment]
I found "menu4" and "menu4.setIconAnimated("false"). But it still won't work in my app

**Comment by whowazit** [comment]
I just restarted my android studio and then it works..hmmp..such magic..Thank you though..Thanks a bunch
