### ISSUE TITLE
setting ImageDrawable as android-iconify's IconDrawable

### ISSUE THREAD

**Issue by aacanakin** [Clans/FloatingActionButton#55]
Hello,
I'm using android-iconify for setting floating action button's drawable. However, when I set the `ImageDrawable` as `IconDrawable` the following occurs;
```java
mNewEventButton.setImageDrawable(new IconDrawable(mContext, Iconify.IconValue.fa_calendar).colorRes(R.color.white).actionBarSize());
mNewMessageButton.setImageDrawable(new IconDrawable(mContext, Iconify.IconValue.fa_envelope).colorRes(R.color.white).actionBarSize());
```
![floating_action_button_bug](https://cloud.githubusercontent.com/assets/515372/7878691/cdf0d2ea-05f1-11e5-8826-47fb6a33e77c.png)

NOTE: I've tried decrementing icon size and setting padding of button to 0. It doesn't work

Is there any way to fix this?

**Comment by iraupph** [comment]
Have you tried using [Android Iconics](https://github.com/mikepenz/Android-Iconics)?
I'm using this lib and instantiating similarly to you:
```java
mImagePickerFab.setImageDrawable(new IconicsDrawable(getApplicationContext(), GoogleMaterial.Icon.gmd_check).color(Color.WHITE).actionBarSize());
```
and I'm not having those problems.
I don't know if this is and option to you, but it's and alternative.

**Comment by aacanakin** [comment]
It works. Thanks !

**Comment by iraupph** [comment]
Just complementing, I don't know if there is another way to do this, but to match the expected FAB icon size I had to set it manually like this:
```java
mMyFab.setImageDrawable(new IconicsDrawable(getApplicationContext(), GoogleMaterial.Icon.gmd_attach_file).color(Color.WHITE).sizeDp(16));
```
Notice the `.sizeDp(16)` at the end.
Cheers!
