### ISSUE TITLE
FloatingActionMenu show/hide like FloatingActionButton

### ISSUE THREAD

**Issue by TomasValenta** [Clans/FloatingActionButton#60]
Hello,
can be FloatingActionMenu button hidden like FloatingActionButton on [this line](https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/MainActivity.java#L66) when onScrollView started?
I can't find method like:

```java
floatingActionMenu.show();
floatingActionMenu.hide();
```

**Comment by Clans** [comment]
Hello,
please use `FloatingActionMenu.hideMenuButton(true/false)`.

**Comment by TomasValenta** [comment]
I'm sorry,
my mistake ;) Thank you!
