### ISSUE TITLE
When menu is collapsed menu items still take space

### ISSUE THREAD

**Issue by Zakay** [Clans/FloatingActionButton#62]
I'm guessing it's because it uses visibility=invisible instead of setting it to gone.
I'm not totally sure why this design choice was made, but it would be much cleaner if there was a parameter instead for making certain buttons not appearing when menu is opened.

fab:active="true|false"

This way space wouldn't be cluttered with invisible buttons and they wouldn't affect layout around them.

**Comment by Clans** [comment]
I've made some changes. Now you can use `FloatingActionButton.setVisibility(GONE)` to hide the button with its label from the menu. Is that what you've asked for?

**Comment by Zakay** [comment]
Great!
