### ISSUE TITLE
Can we change the color of the float button and menu button programmatically?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [Clans/FloatingActionButton#65]
Hi!

Thanks for bringing it back to API level 4. 

I want to apply the color for the Float Button and menu programmatically, there is only one method 'setBackgroundColor' but it is changing the square behind floating button and menu. 

Thanks.

**Comment by Clans** [comment]
Hello,
For the FloatingActionMenu see the lines 770-810:
https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/java/com/github/clans/fab/FloatingActionMenu.java#L770
For the FloatingActionButton see the lines 831-874:
https://github.com/Clans/FloatingActionButton/blob/master/library/src/main/java/com/github/clans/fab/FloatingActionButton.java#L831

**Comment by Shajeel-Afzal** [comment]
Thanks @Clans
