### ISSUE TITLE
disable background when menu is opened

### ISSUE THREAD

**Issue by Slake07** [Clans/FloatingActionButton#66]
i am showing listivew with floating menu. on clicking list items, i am showing details about it. and when menu is opened, listview should not be work. which is working right now. please make it correct.

**Comment by Clans** [comment]
Please try this: `FloatingActionMenu.setClosedOnTouchOutside(true)`.

**Comment by Slake07** [comment]
yeah it works on for click but i am using longpress on list item.

**Comment by Clans** [comment]
I've just checked. OnItemLongClickListener works just fine with the FloatinActionMenu opened for me.

**Comment by MFlisar** [comment]
For me, this does not work at all. Using a FAB in a `RelativeLayout` or in an `FrameLayout` does make no difference, the FAB is on top, but when opened, the background is always touchable...

**Comment by alexpadillarosas** [comment]
Congrats mate!, you really did a nice job!.
Well im facing a similar situation using the option FloatingActionMenu.setClosedOnTouchOutside(true). however the fab menu close only if i clicked close to it. not if i clicked on the list view. do you have any idea of what could be happened? I will attach an image of a part of my activity_main probably is related to the way how i created.
![screen shot 2015-09-14 at 10 48 13 pm](https://cloud.githubusercontent.com/assets/4823319/9849917/89d55086-5b32-11e5-8c32-7e36861602fd.png)

**Comment by MFlisar** [comment]
I had the same problem... The menu has to somehow catch the click, so use `match_parent` for width and height instead of `wrap_content`...  Otherwise it will only wrap the expanded content, which mostly is not enough...

**Comment by Clans** [comment]
Yes. `FloatingActionMenu` is a `ViewGroup` so set its width and height properly.
