### ISSUE TITLE
fab gets hidden if keyboard appears - and never come back

### ISSUE THREAD

**Issue by Rainer-Lang** [Clans/FloatingActionButton#68]

**Comment by Clans** [comment]
I can't reproduce this issue. Could you provide some of your code?

**Comment by Rainer-Lang** [comment]
I use a RecyclerView with CardView.
The cards have 4 EditTexts inside.
After click in one edittext the keyboard is shown - and in some(!) cases the fab is hidden and I never get it back because I can't scroll up to get the fab back.

**Comment by Clans** [comment]
Not sure if this an issue in the library. You always can show the FAB manually for example when the keyboard gets hide.

**Comment by Rainer-Lang** [comment]
You are right. Thanks for the tipp. :-) 
This helps.
