### ISSUE TITLE
Error:(10, 0) Could not find property 'VERSION_CODE' on project ':library'.

### ISSUE THREAD

**Issue by schpitz** [Clans/FloatingActionButton#75]
After downloading and opening this project, i'm getting this error.
Error:(10, 0) Could not find property 'VERSION_CODE' on project ':library'.

The problem is with the library folder, not the sample.
I had tried to fix it manually, but it just keep appearing, and I can't play the sample module.
I'm using Android Studio v1.2.2.

**Comment by Clans** [comment]
Just replace int build.gradle the line:
`versionCode Integer.parseInt(project.VERSION_CODE)`
with:
`versionCode any_number`

**Comment by schpitz** [comment]
already tried it!
still doesn't work...

**Comment by Clans** [comment]
Have you made teh same for the sample project and for the `versionName project.VERSION_NAME` line as well?

**Comment by schpitz** [comment]
I get the following error:
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by Clans** [comment]
Try to comment out the line: `apply from: '../gradle-mvn-push.gradle'` in the library's `build.gradle`.

**Comment by schpitz** [comment]
Hallelujah 
Thanks man!

**Comment by Clans** [comment]
You're welcome. ;)
