### ISSUE TITLE
Reason for adjustForOvershoot

### ISSUE THREAD

**Issue by aalap-shah** [Clans/FloatingActionButton#76]
Thank you for your library , I have been using your library and wanted to modify for a reason. Can you tell me why do we have adjustForOvershoot function. 

Thanks

**Comment by Clans** [comment]
That is used for OvershootInterpolator.

**Comment by aalap-shah** [comment]
Thanks. Basically my use-case is that I have dynamically created FAB inside FAM. Now as the number of FAB's grow the view goes beyond the screen height. So added the FAM inside a ScrollView. Now when the FAM is expanded and my scrollview is scrolled at the top, there is too much extra space at the top. Any suggestions on how should I solve this ?
Thanks in advance.

**Comment by Clans** [comment]
I've made a minor fix. Now the height should be calculated better. Please use the version 1.5.2.

**Comment by aalap-shah** [comment]
Hey thanks for the fix. I think there is 1 more issue. In FloatingActionMenu.java file inside onMeasure function on line number 318, instead of using (for height adjustment)
mButtonSpacing * (getChildCount() - 1) 
should it be 
mButtonSpacing * (mButtonsCount - 1) 
As labels are also children the height calculation adds extra space for labels too. 

Thanks,

**Comment by aalap-shah** [comment]
Hey, Did you get time to look at the above issue. If you wish I can send a pull request for it.

**Comment by Clans** [comment]
You're right. Fixed in 1.5.3. Thanks!
