### ISSUE TITLE
FloatingActionButton sample is not working properly for animated fab menu.

### ISSUE THREAD

**Issue by VishalAdhau** [Clans/FloatingActionButton#78]
Tested on
Model number : Micromax A290
Android version : 4.4.2

FloatingActionButton sample is not working for animated fab menu on Android 4.4.2. It was working fine on FloatingActionButton version 1.5.0.
Root cause : 
In version 1.5.1, mMenuOpened = true is moved inside the postDelay(). On Android version 4.4.2 OnLayout() gets called for each item after fab.show(animated) and there is a mMenuOpened check for fab item that hides the fab menu button.

**Comment by Clans** [comment]
I've checked on Android Emulator 4.4.4 and on Samsung Galaxy S5 4.4.2 - everything works fine.

**Comment by VishalAdhau** [comment]
its reproducible on below device
Model number : Micromax A290
Android version : 4.4.2

Please check the video
https://www.dropbox.com/s/jlhgqgmmymflrm3/VID_20150630_132114.mp4?dl=1

**Comment by VishalAdhau** [comment]
Is there any specific reason of adding below code in onLayout() of FloatingActionMenu.java?
if (!mMenuOpened) {
         fab.hide(false);
}

In my case onMeasure() and onLayout() gets called multiple times in between animation to show the fab. In this case changed parameter in onLayout() has false value.

Issue can be handled by checking changed parameter value in onLayout(), if changed parameter is false, no need to layout the children's in OnLayout().

Please let me know if you need inputs.

**Comment by Clans** [comment]
Could you please check this build on your device?
https://dl.dropboxusercontent.com/u/4981502/sample-debug.apk

**Comment by VishalAdhau** [comment]
Thanks a lot,
Fab animation works fine, I think you missed to handle same for fab labels. Please also handle it for fab label, there is same check for labels in onLayout().
if (!mMenuOpened) {
                    label.setVisibility(INVISIBLE);
                }

Please check the video(using sample-debug.apk) 
https://www.dropbox.com/s/51n3hea2feyx3t8/VID_20150709_130507.mp4?dl=1

**Comment by VishalAdhau** [comment]
Thanks Clans,
It works awesome.
