### ISSUE TITLE
Support alternatives to rotation on FAM icon

### ISSUE THREAD

**Issue by commonsguy** [Clans/FloatingActionButton#80]
Right now, AFAICT, we do not have control over the state change of the FAM icon when the FAM is opened and closed. The one-and-only icon rotates, presumably to support the `+`-or-`x` pattern. That's a cool default, but it is less than ideal when using most other icons. I happen to be using a settings "gear" icon, and while the icon at least looks OK in both rotations, there's no visible difference to the user between the two states.

What would be slick is the option to provide icons and animations for the closed and opened states, defaulting to what is there now. For example, one could provide a settings icon and an `x` icon, with animations to fade the old one out and fade the new one in.

Less slick, though much simpler, would be to support a `StateListDrawable` for the icon, using normal and another state (activated?) for closed and open. That way, we would have the option of supplying a `StateListDrawable` that uses different images for the two states, though there would be a "smash cut" between them. This could be as simple as calling `setActivated()` on `mImageToggle` at appropriate points to switch on and off the activated state. This might also allow for us to eventually use an `AnimatedStateListDrawable` (added in API Level 21) for those of us with a high enough `minSdkVersion`.

**Comment by Clans** [comment]
Please have a look at the sample code:
https://github.com/Clans/FloatingActionButton/blob/master/sample/src/main/java/com/github/clans/fab/sample/FloatingMenusActivity.java#L151
It's the green button on demo video. Is that what you looking for?

**Comment by commonsguy** [comment]
Mea culpa. That definitely looks like it's what I had in mind. Not sure how I missed that when reviewing the FAM icon implementation. Many thanks!
