### ISSUE TITLE
Issue: can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Clans/FloatingActionButton#86]
When trying to import the whole project, I get this :
![untitled20150708003725](https://cloud.githubusercontent.com/assets/5357526/8557971/b32e7cbe-2509-11e5-826e-8d7b7488ae96.png)

and when I try to use it in my own project, I get this:
![untitled20150708003809](https://cloud.githubusercontent.com/assets/5357526/8557972/b8522ccc-2509-11e5-9d1c-cf3668f0d7ad.png)

What should I do? For both cases, it failed importing...

**Comment by Clans** [comment]
Please check this issue: https://github.com/Clans/FloatingActionButton/issues/75

**Comment by AndroidDeveloperLB** [comment]
So it's not solved yet I see. Can you please fix the project, so that
everyone would be able to import it easily?

**Comment by Clans** [comment]
As for the second error you have it's because of your project uses minSdkVersion - 9 and this library has minSdkVersion - 14.

**Comment by AndroidDeveloperLB** [comment]
Why is it 14? The min API for the support library and the design library is 7 ...

**Comment by rajuashok** [comment]
Use this:

compile 'com.github.clans:fab:1.5.3'

The README has a mistake and states 1.5.4 which is wrong.

**Comment by AndroidDeveloperLB** [comment]
ok, I've imported the project by setting the "versionCode" and "versionName" to normal values, and also removed the "apply from: '../gradle-mvn-push.gradle'" part.
Please fix it in the repo itself.

Also, please consider using the same min API as the design library.
