### ISSUE TITLE
RecycleView

### ISSUE THREAD

**Issue by devGuilherme** [Clans/FloatingActionButton#91]
Is posible use this lib with recycle view and caview layout?

**Comment by Rainer-Lang** [comment]
Possible.

**Comment by devGuilherme** [comment]
and in android.support.v4.widget.SwipeRefreshLayout ?

**Comment by devGuilherme** [comment]
this is my xml:
===============================================================================
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipe_layout">    
    
    <android.support.v7.widget.RecyclerView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/rv"
    />

  <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginRight="10dp"
        android:layout_marginBottom="10dp"
        android:layout_marginLeft="10dp"
        app:menu_fab_size="normal"
        app:menu_showShadow="true"
        app:menu_shadowColor="#66000000"
        app:menu_shadowRadius="4dp"
        app:menu_shadowXOffset="1dp"
        app:menu_shadowYOffset="3dp"
        app:menu_colorNormal="#DA4336"
        app:menu_colorPressed="#E75043"
        app:menu_colorRipple="#99FFFFFF"
        app:menu_animationDelayPerItem="50"
        app:menu_icon="@drawable/fab_add"
        app:menu_buttonSpacing="0dp"
        app:menu_labels_margin="0dp"
        app:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
        app:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
        app:menu_labels_paddingTop="4dp"
        app:menu_labels_paddingRight="8dp"
        app:menu_labels_paddingBottom="4dp"
        app:menu_labels_paddingLeft="8dp"
        app:menu_labels_padding="8dp"
        app:menu_labels_textColor="#FFFFFF"
        app:menu_labels_textSize="14sp"
        app:menu_labels_cornerRadius="3dp"
        app:menu_labels_colorNormal="#333333"
        app:menu_labels_colorPressed="#444444"
        app:menu_labels_colorRipple="#66FFFFFF"
        app:menu_labels_showShadow="true"
        app:menu_labels_singleLine="false"
        app:menu_labels_ellipsize="none"
        app:menu_labels_maxLines="-1"
        app:menu_labels_position="left"
        app:menu_openDirection="up"
        app:menu_backgroundColor="@android:color/transparent">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/menu_item"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_action_incon_notificao"
            app:fab_size="mini"
            app:fab_label="Notificações" />

    </com.github.clans.fab.FloatingActionMenu>
    
    
</android.support.v4.widget.SwipeRefreshLayout>

**Comment by devGuilherme** [comment]
I'm try to use this in eclipse

**Comment by devGuilherme** [comment]
alright thanks for exelente library!
