### ISSUE TITLE
floating action menus and buttons not getting the styles

### ISSUE THREAD

**Issue by 3nomis** [Clans/FloatingActionButton#97]
I don't know why my floating action button inside a CoordinatorLayout is not getting any custom styles, even if I write them straight in the xml file it doesn't appear with the color and the attributes I set. 
Is it only me having this issue?

**Comment by mmazzarolo** [comment]
I had your same problem.

Fixed changing the namespace from:
 `xmlns:fab="http://schemas.android.com/tools"`

To:
`xmlns:fab="http://schemas.android.com/apk/res-auto"`

Also, make sure to implement [correct behavior] (https://github.com/Clans/FloatingActionButton/issues/61).
