### ISSUE TITLE
Add label to FloatingActionMenu

### ISSUE THREAD

**Issue by dan41k** [Clans/FloatingActionButton#98]
Can I add label to mMenuButton in FloatingActionMenu when it has opened?

**Comment by miomao656** [comment]
Also interested in this. I am trying to implement Google Inbox app alike behavior, to change icon on menu opened and set lebel on menu button.  I see this is on schedule for 1.6.0, and i have tried to merge pull request https://github.com/Clans/FloatingActionButton/pull/32 but it does not work, and i have some difficulty understanding why.
